/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type {
	DtoErrorResponse,
	GetV1VaultBalance200,
	GetV1VaultBalanceParams,
	GetV1VaultTransactions200,
	GetV1VaultTransactionsParams,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getV1VaultBalanceResponse200 = {
	data: GetV1VaultBalance200;
	status: 200;
};

export type getV1VaultBalanceResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type getV1VaultBalanceResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type getV1VaultBalanceResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type getV1VaultBalanceResponseSuccess = getV1VaultBalanceResponse200 & {
	headers: Headers;
};
export type getV1VaultBalanceResponseError = (
	| getV1VaultBalanceResponse401
	| getV1VaultBalanceResponse403
	| getV1VaultBalanceResponse500
) & {
	headers: Headers;
};

export type getV1VaultBalanceResponse =
	| getV1VaultBalanceResponseSuccess
	| getV1VaultBalanceResponseError;

export const getGetV1VaultBalanceUrl = (params?: GetV1VaultBalanceParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/vault/balance?${stringifiedParams}`
		: `/v1/vault/balance`;
};

/**
 * Get current vault balance and total student savings
 * @summary Get vault balance
 */
export const getV1VaultBalance = async (
	params?: GetV1VaultBalanceParams,
	options?: RequestInit,
): Promise<getV1VaultBalanceResponse> => {
	return customInstance<getV1VaultBalanceResponse>(
		getGetV1VaultBalanceUrl(params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetV1VaultBalanceQueryKey = (
	params?: GetV1VaultBalanceParams,
) => {
	return [`/v1/vault/balance`, ...(params ? [params] : [])] as const;
};

export const getGetV1VaultBalanceQueryOptions = <
	TData = Awaited<ReturnType<typeof getV1VaultBalance>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultBalanceParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultBalance>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetV1VaultBalanceQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getV1VaultBalance>>
	> = ({ signal }) => getV1VaultBalance(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getV1VaultBalance>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1VaultBalanceQueryResult = NonNullable<
	Awaited<ReturnType<typeof getV1VaultBalance>>
>;
export type GetV1VaultBalanceQueryError = DtoErrorResponse;

export function useGetV1VaultBalance<
	TData = Awaited<ReturnType<typeof getV1VaultBalance>>,
	TError = DtoErrorResponse,
>(
	params: undefined | GetV1VaultBalanceParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultBalance>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1VaultBalance>>,
					TError,
					Awaited<ReturnType<typeof getV1VaultBalance>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1VaultBalance<
	TData = Awaited<ReturnType<typeof getV1VaultBalance>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultBalanceParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultBalance>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1VaultBalance>>,
					TError,
					Awaited<ReturnType<typeof getV1VaultBalance>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1VaultBalance<
	TData = Awaited<ReturnType<typeof getV1VaultBalance>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultBalanceParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultBalance>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get vault balance
 */

export function useGetV1VaultBalance<
	TData = Awaited<ReturnType<typeof getV1VaultBalance>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultBalanceParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultBalance>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetV1VaultBalanceQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type getV1VaultTransactionsResponse200 = {
	data: GetV1VaultTransactions200;
	status: 200;
};

export type getV1VaultTransactionsResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type getV1VaultTransactionsResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type getV1VaultTransactionsResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type getV1VaultTransactionsResponseSuccess =
	getV1VaultTransactionsResponse200 & {
		headers: Headers;
	};
export type getV1VaultTransactionsResponseError = (
	| getV1VaultTransactionsResponse401
	| getV1VaultTransactionsResponse403
	| getV1VaultTransactionsResponse500
) & {
	headers: Headers;
};

export type getV1VaultTransactionsResponse =
	| getV1VaultTransactionsResponseSuccess
	| getV1VaultTransactionsResponseError;

export const getGetV1VaultTransactionsUrl = (
	params?: GetV1VaultTransactionsParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/vault/transactions?${stringifiedParams}`
		: `/v1/vault/transactions`;
};

/**
 * Get a paginated list of vault transactions
 * @summary Get vault transactions
 */
export const getV1VaultTransactions = async (
	params?: GetV1VaultTransactionsParams,
	options?: RequestInit,
): Promise<getV1VaultTransactionsResponse> => {
	return customInstance<getV1VaultTransactionsResponse>(
		getGetV1VaultTransactionsUrl(params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetV1VaultTransactionsQueryKey = (
	params?: GetV1VaultTransactionsParams,
) => {
	return [`/v1/vault/transactions`, ...(params ? [params] : [])] as const;
};

export const getGetV1VaultTransactionsQueryOptions = <
	TData = Awaited<ReturnType<typeof getV1VaultTransactions>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultTransactionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultTransactions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetV1VaultTransactionsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getV1VaultTransactions>>
	> = ({ signal }) =>
		getV1VaultTransactions(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getV1VaultTransactions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1VaultTransactionsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getV1VaultTransactions>>
>;
export type GetV1VaultTransactionsQueryError = DtoErrorResponse;

export function useGetV1VaultTransactions<
	TData = Awaited<ReturnType<typeof getV1VaultTransactions>>,
	TError = DtoErrorResponse,
>(
	params: undefined | GetV1VaultTransactionsParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultTransactions>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1VaultTransactions>>,
					TError,
					Awaited<ReturnType<typeof getV1VaultTransactions>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1VaultTransactions<
	TData = Awaited<ReturnType<typeof getV1VaultTransactions>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultTransactionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultTransactions>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1VaultTransactions>>,
					TError,
					Awaited<ReturnType<typeof getV1VaultTransactions>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1VaultTransactions<
	TData = Awaited<ReturnType<typeof getV1VaultTransactions>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultTransactionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultTransactions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get vault transactions
 */

export function useGetV1VaultTransactions<
	TData = Awaited<ReturnType<typeof getV1VaultTransactions>>,
	TError = DtoErrorResponse,
>(
	params?: GetV1VaultTransactionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1VaultTransactions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetV1VaultTransactionsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
