/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterTahunAjaranRouteImport } from './routes/master/tahun-ajaran'
import { Route as MasterJenjangRouteImport } from './routes/master/jenjang'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterTahunAjaranRoute = MasterTahunAjaranRouteImport.update({
  id: '/master/tahun-ajaran',
  path: '/master/tahun-ajaran',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterJenjangRoute = MasterJenjangRouteImport.update({
  id: '/master/jenjang',
  path: '/master/jenjang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/master/jenjang' | '/master/tahun-ajaran'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/master/jenjang' | '/master/tahun-ajaran'
  id: '__root__' | '/' | '/login' | '/master/jenjang' | '/master/tahun-ajaran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MasterJenjangRoute: typeof MasterJenjangRoute
  MasterTahunAjaranRoute: typeof MasterTahunAjaranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/tahun-ajaran': {
      id: '/master/tahun-ajaran'
      path: '/master/tahun-ajaran'
      fullPath: '/master/tahun-ajaran'
      preLoaderRoute: typeof MasterTahunAjaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/jenjang': {
      id: '/master/jenjang'
      path: '/master/jenjang'
      fullPath: '/master/jenjang'
      preLoaderRoute: typeof MasterJenjangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MasterJenjangRoute: MasterJenjangRoute,
  MasterTahunAjaranRoute: MasterTahunAjaranRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
