/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiswaIndexRouteImport } from './routes/siswa/index'
import { Route as SiswaProgresiRouteImport } from './routes/siswa/progresi'
import { Route as MasterTahunAjaranRouteImport } from './routes/master/tahun-ajaran'
import { Route as MasterRombelRouteImport } from './routes/master/rombel'
import { Route as MasterJenjangRouteImport } from './routes/master/jenjang'
import { Route as MasterJenisPembayaranRouteImport } from './routes/master/jenis-pembayaran'
import { Route as MasterDiskonRouteImport } from './routes/master/diskon'
import { Route as KeuanganPembayaranRouteImport } from './routes/keuangan/pembayaran'
import { Route as KeuanganBillingRouteImport } from './routes/keuangan/billing'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIndexRoute = SiswaIndexRouteImport.update({
  id: '/siswa/',
  path: '/siswa/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaProgresiRoute = SiswaProgresiRouteImport.update({
  id: '/siswa/progresi',
  path: '/siswa/progresi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterTahunAjaranRoute = MasterTahunAjaranRouteImport.update({
  id: '/master/tahun-ajaran',
  path: '/master/tahun-ajaran',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRombelRoute = MasterRombelRouteImport.update({
  id: '/master/rombel',
  path: '/master/rombel',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterJenjangRoute = MasterJenjangRouteImport.update({
  id: '/master/jenjang',
  path: '/master/jenjang',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterJenisPembayaranRoute = MasterJenisPembayaranRouteImport.update({
  id: '/master/jenis-pembayaran',
  path: '/master/jenis-pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDiskonRoute = MasterDiskonRouteImport.update({
  id: '/master/diskon',
  path: '/master/diskon',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganPembayaranRoute = KeuanganPembayaranRouteImport.update({
  id: '/keuangan/pembayaran',
  path: '/keuangan/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganBillingRoute = KeuanganBillingRouteImport.update({
  id: '/keuangan/billing',
  path: '/keuangan/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/keuangan/billing': typeof KeuanganBillingRoute
  '/keuangan/pembayaran': typeof KeuanganPembayaranRoute
  '/master/diskon': typeof MasterDiskonRoute
  '/master/jenis-pembayaran': typeof MasterJenisPembayaranRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/rombel': typeof MasterRombelRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
  '/siswa/progresi': typeof SiswaProgresiRoute
  '/siswa/': typeof SiswaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/keuangan/billing': typeof KeuanganBillingRoute
  '/keuangan/pembayaran': typeof KeuanganPembayaranRoute
  '/master/diskon': typeof MasterDiskonRoute
  '/master/jenis-pembayaran': typeof MasterJenisPembayaranRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/rombel': typeof MasterRombelRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
  '/siswa/progresi': typeof SiswaProgresiRoute
  '/siswa': typeof SiswaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/keuangan/billing': typeof KeuanganBillingRoute
  '/keuangan/pembayaran': typeof KeuanganPembayaranRoute
  '/master/diskon': typeof MasterDiskonRoute
  '/master/jenis-pembayaran': typeof MasterJenisPembayaranRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/rombel': typeof MasterRombelRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
  '/siswa/progresi': typeof SiswaProgresiRoute
  '/siswa/': typeof SiswaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/keuangan/billing'
    | '/keuangan/pembayaran'
    | '/master/diskon'
    | '/master/jenis-pembayaran'
    | '/master/jenjang'
    | '/master/rombel'
    | '/master/tahun-ajaran'
    | '/siswa/progresi'
    | '/siswa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/keuangan/billing'
    | '/keuangan/pembayaran'
    | '/master/diskon'
    | '/master/jenis-pembayaran'
    | '/master/jenjang'
    | '/master/rombel'
    | '/master/tahun-ajaran'
    | '/siswa/progresi'
    | '/siswa'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/keuangan/billing'
    | '/keuangan/pembayaran'
    | '/master/diskon'
    | '/master/jenis-pembayaran'
    | '/master/jenjang'
    | '/master/rombel'
    | '/master/tahun-ajaran'
    | '/siswa/progresi'
    | '/siswa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  KeuanganBillingRoute: typeof KeuanganBillingRoute
  KeuanganPembayaranRoute: typeof KeuanganPembayaranRoute
  MasterDiskonRoute: typeof MasterDiskonRoute
  MasterJenisPembayaranRoute: typeof MasterJenisPembayaranRoute
  MasterJenjangRoute: typeof MasterJenjangRoute
  MasterRombelRoute: typeof MasterRombelRoute
  MasterTahunAjaranRoute: typeof MasterTahunAjaranRoute
  SiswaProgresiRoute: typeof SiswaProgresiRoute
  SiswaIndexRoute: typeof SiswaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/': {
      id: '/siswa/'
      path: '/siswa'
      fullPath: '/siswa/'
      preLoaderRoute: typeof SiswaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/progresi': {
      id: '/siswa/progresi'
      path: '/siswa/progresi'
      fullPath: '/siswa/progresi'
      preLoaderRoute: typeof SiswaProgresiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/tahun-ajaran': {
      id: '/master/tahun-ajaran'
      path: '/master/tahun-ajaran'
      fullPath: '/master/tahun-ajaran'
      preLoaderRoute: typeof MasterTahunAjaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/rombel': {
      id: '/master/rombel'
      path: '/master/rombel'
      fullPath: '/master/rombel'
      preLoaderRoute: typeof MasterRombelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/jenjang': {
      id: '/master/jenjang'
      path: '/master/jenjang'
      fullPath: '/master/jenjang'
      preLoaderRoute: typeof MasterJenjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/jenis-pembayaran': {
      id: '/master/jenis-pembayaran'
      path: '/master/jenis-pembayaran'
      fullPath: '/master/jenis-pembayaran'
      preLoaderRoute: typeof MasterJenisPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/diskon': {
      id: '/master/diskon'
      path: '/master/diskon'
      fullPath: '/master/diskon'
      preLoaderRoute: typeof MasterDiskonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/pembayaran': {
      id: '/keuangan/pembayaran'
      path: '/keuangan/pembayaran'
      fullPath: '/keuangan/pembayaran'
      preLoaderRoute: typeof KeuanganPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/billing': {
      id: '/keuangan/billing'
      path: '/keuangan/billing'
      fullPath: '/keuangan/billing'
      preLoaderRoute: typeof KeuanganBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  KeuanganBillingRoute: KeuanganBillingRoute,
  KeuanganPembayaranRoute: KeuanganPembayaranRoute,
  MasterDiskonRoute: MasterDiskonRoute,
  MasterJenisPembayaranRoute: MasterJenisPembayaranRoute,
  MasterJenjangRoute: MasterJenjangRoute,
  MasterRombelRoute: MasterRombelRoute,
  MasterTahunAjaranRoute: MasterTahunAjaranRoute,
  SiswaProgresiRoute: SiswaProgresiRoute,
  SiswaIndexRoute: SiswaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
