/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiswaIndexRouteImport } from './routes/siswa/index'
import { Route as SiswaProgresiRouteImport } from './routes/siswa/progresi'
import { Route as MasterTahunAjaranRouteImport } from './routes/master/tahun-ajaran'
import { Route as MasterRombelRouteImport } from './routes/master/rombel'
import { Route as MasterJenjangRouteImport } from './routes/master/jenjang'
import { Route as MasterJenisPembayaranRouteImport } from './routes/master/jenis-pembayaran'
import { Route as MasterDiskonRouteImport } from './routes/master/diskon'
import { Route as KeuanganTabunganRouteImport } from './routes/keuangan/tabungan'
import { Route as KeuanganPembayaranRouteImport } from './routes/keuangan/pembayaran'
import { Route as KeuanganKasRouteImport } from './routes/keuangan/kas'
import { Route as KeuanganBillingRouteImport } from './routes/keuangan/billing'
import { Route as KeuanganTabunganIndexRouteImport } from './routes/keuangan/tabungan/index'
import { Route as KeuanganPembayaranIndexRouteImport } from './routes/keuangan/pembayaran/index'
import { Route as KeuanganKasIndexRouteImport } from './routes/keuangan/kas/index'
import { Route as KeuanganBillingIndexRouteImport } from './routes/keuangan/billing/index'
import { Route as KeuanganTabunganTabunganIdRouteImport } from './routes/keuangan/tabungan/$tabunganId'
import { Route as KeuanganPembayaranHistoryRouteImport } from './routes/keuangan/pembayaran/history'
import { Route as KeuanganKasRekonsiliasiRouteImport } from './routes/keuangan/kas/rekonsiliasi'
import { Route as KeuanganKasMutasiRouteImport } from './routes/keuangan/kas/mutasi'
import { Route as KeuanganBillingHistoryIndexRouteImport } from './routes/keuangan/billing/history/index'
import { Route as KeuanganBillingHistoryPeriodeRouteImport } from './routes/keuangan/billing/history/$periode'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIndexRoute = SiswaIndexRouteImport.update({
  id: '/siswa/',
  path: '/siswa/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaProgresiRoute = SiswaProgresiRouteImport.update({
  id: '/siswa/progresi',
  path: '/siswa/progresi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterTahunAjaranRoute = MasterTahunAjaranRouteImport.update({
  id: '/master/tahun-ajaran',
  path: '/master/tahun-ajaran',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRombelRoute = MasterRombelRouteImport.update({
  id: '/master/rombel',
  path: '/master/rombel',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterJenjangRoute = MasterJenjangRouteImport.update({
  id: '/master/jenjang',
  path: '/master/jenjang',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterJenisPembayaranRoute = MasterJenisPembayaranRouteImport.update({
  id: '/master/jenis-pembayaran',
  path: '/master/jenis-pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDiskonRoute = MasterDiskonRouteImport.update({
  id: '/master/diskon',
  path: '/master/diskon',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganTabunganRoute = KeuanganTabunganRouteImport.update({
  id: '/keuangan/tabungan',
  path: '/keuangan/tabungan',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganPembayaranRoute = KeuanganPembayaranRouteImport.update({
  id: '/keuangan/pembayaran',
  path: '/keuangan/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganKasRoute = KeuanganKasRouteImport.update({
  id: '/keuangan/kas',
  path: '/keuangan/kas',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganBillingRoute = KeuanganBillingRouteImport.update({
  id: '/keuangan/billing',
  path: '/keuangan/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganTabunganIndexRoute = KeuanganTabunganIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeuanganTabunganRoute,
} as any)
const KeuanganPembayaranIndexRoute = KeuanganPembayaranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeuanganPembayaranRoute,
} as any)
const KeuanganKasIndexRoute = KeuanganKasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeuanganKasRoute,
} as any)
const KeuanganBillingIndexRoute = KeuanganBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeuanganBillingRoute,
} as any)
const KeuanganTabunganTabunganIdRoute =
  KeuanganTabunganTabunganIdRouteImport.update({
    id: '/$tabunganId',
    path: '/$tabunganId',
    getParentRoute: () => KeuanganTabunganRoute,
  } as any)
const KeuanganPembayaranHistoryRoute =
  KeuanganPembayaranHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => KeuanganPembayaranRoute,
  } as any)
const KeuanganKasRekonsiliasiRoute = KeuanganKasRekonsiliasiRouteImport.update({
  id: '/rekonsiliasi',
  path: '/rekonsiliasi',
  getParentRoute: () => KeuanganKasRoute,
} as any)
const KeuanganKasMutasiRoute = KeuanganKasMutasiRouteImport.update({
  id: '/mutasi',
  path: '/mutasi',
  getParentRoute: () => KeuanganKasRoute,
} as any)
const KeuanganBillingHistoryIndexRoute =
  KeuanganBillingHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => KeuanganBillingRoute,
  } as any)
const KeuanganBillingHistoryPeriodeRoute =
  KeuanganBillingHistoryPeriodeRouteImport.update({
    id: '/history/$periode',
    path: '/history/$periode',
    getParentRoute: () => KeuanganBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/keuangan/billing': typeof KeuanganBillingRouteWithChildren
  '/keuangan/kas': typeof KeuanganKasRouteWithChildren
  '/keuangan/pembayaran': typeof KeuanganPembayaranRouteWithChildren
  '/keuangan/tabungan': typeof KeuanganTabunganRouteWithChildren
  '/master/diskon': typeof MasterDiskonRoute
  '/master/jenis-pembayaran': typeof MasterJenisPembayaranRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/rombel': typeof MasterRombelRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
  '/siswa/progresi': typeof SiswaProgresiRoute
  '/siswa/': typeof SiswaIndexRoute
  '/keuangan/kas/mutasi': typeof KeuanganKasMutasiRoute
  '/keuangan/kas/rekonsiliasi': typeof KeuanganKasRekonsiliasiRoute
  '/keuangan/pembayaran/history': typeof KeuanganPembayaranHistoryRoute
  '/keuangan/tabungan/$tabunganId': typeof KeuanganTabunganTabunganIdRoute
  '/keuangan/billing/': typeof KeuanganBillingIndexRoute
  '/keuangan/kas/': typeof KeuanganKasIndexRoute
  '/keuangan/pembayaran/': typeof KeuanganPembayaranIndexRoute
  '/keuangan/tabungan/': typeof KeuanganTabunganIndexRoute
  '/keuangan/billing/history/$periode': typeof KeuanganBillingHistoryPeriodeRoute
  '/keuangan/billing/history/': typeof KeuanganBillingHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master/diskon': typeof MasterDiskonRoute
  '/master/jenis-pembayaran': typeof MasterJenisPembayaranRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/rombel': typeof MasterRombelRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
  '/siswa/progresi': typeof SiswaProgresiRoute
  '/siswa': typeof SiswaIndexRoute
  '/keuangan/kas/mutasi': typeof KeuanganKasMutasiRoute
  '/keuangan/kas/rekonsiliasi': typeof KeuanganKasRekonsiliasiRoute
  '/keuangan/pembayaran/history': typeof KeuanganPembayaranHistoryRoute
  '/keuangan/tabungan/$tabunganId': typeof KeuanganTabunganTabunganIdRoute
  '/keuangan/billing': typeof KeuanganBillingIndexRoute
  '/keuangan/kas': typeof KeuanganKasIndexRoute
  '/keuangan/pembayaran': typeof KeuanganPembayaranIndexRoute
  '/keuangan/tabungan': typeof KeuanganTabunganIndexRoute
  '/keuangan/billing/history/$periode': typeof KeuanganBillingHistoryPeriodeRoute
  '/keuangan/billing/history': typeof KeuanganBillingHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/keuangan/billing': typeof KeuanganBillingRouteWithChildren
  '/keuangan/kas': typeof KeuanganKasRouteWithChildren
  '/keuangan/pembayaran': typeof KeuanganPembayaranRouteWithChildren
  '/keuangan/tabungan': typeof KeuanganTabunganRouteWithChildren
  '/master/diskon': typeof MasterDiskonRoute
  '/master/jenis-pembayaran': typeof MasterJenisPembayaranRoute
  '/master/jenjang': typeof MasterJenjangRoute
  '/master/rombel': typeof MasterRombelRoute
  '/master/tahun-ajaran': typeof MasterTahunAjaranRoute
  '/siswa/progresi': typeof SiswaProgresiRoute
  '/siswa/': typeof SiswaIndexRoute
  '/keuangan/kas/mutasi': typeof KeuanganKasMutasiRoute
  '/keuangan/kas/rekonsiliasi': typeof KeuanganKasRekonsiliasiRoute
  '/keuangan/pembayaran/history': typeof KeuanganPembayaranHistoryRoute
  '/keuangan/tabungan/$tabunganId': typeof KeuanganTabunganTabunganIdRoute
  '/keuangan/billing/': typeof KeuanganBillingIndexRoute
  '/keuangan/kas/': typeof KeuanganKasIndexRoute
  '/keuangan/pembayaran/': typeof KeuanganPembayaranIndexRoute
  '/keuangan/tabungan/': typeof KeuanganTabunganIndexRoute
  '/keuangan/billing/history/$periode': typeof KeuanganBillingHistoryPeriodeRoute
  '/keuangan/billing/history/': typeof KeuanganBillingHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/keuangan/billing'
    | '/keuangan/kas'
    | '/keuangan/pembayaran'
    | '/keuangan/tabungan'
    | '/master/diskon'
    | '/master/jenis-pembayaran'
    | '/master/jenjang'
    | '/master/rombel'
    | '/master/tahun-ajaran'
    | '/siswa/progresi'
    | '/siswa/'
    | '/keuangan/kas/mutasi'
    | '/keuangan/kas/rekonsiliasi'
    | '/keuangan/pembayaran/history'
    | '/keuangan/tabungan/$tabunganId'
    | '/keuangan/billing/'
    | '/keuangan/kas/'
    | '/keuangan/pembayaran/'
    | '/keuangan/tabungan/'
    | '/keuangan/billing/history/$periode'
    | '/keuangan/billing/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/master/diskon'
    | '/master/jenis-pembayaran'
    | '/master/jenjang'
    | '/master/rombel'
    | '/master/tahun-ajaran'
    | '/siswa/progresi'
    | '/siswa'
    | '/keuangan/kas/mutasi'
    | '/keuangan/kas/rekonsiliasi'
    | '/keuangan/pembayaran/history'
    | '/keuangan/tabungan/$tabunganId'
    | '/keuangan/billing'
    | '/keuangan/kas'
    | '/keuangan/pembayaran'
    | '/keuangan/tabungan'
    | '/keuangan/billing/history/$periode'
    | '/keuangan/billing/history'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/keuangan/billing'
    | '/keuangan/kas'
    | '/keuangan/pembayaran'
    | '/keuangan/tabungan'
    | '/master/diskon'
    | '/master/jenis-pembayaran'
    | '/master/jenjang'
    | '/master/rombel'
    | '/master/tahun-ajaran'
    | '/siswa/progresi'
    | '/siswa/'
    | '/keuangan/kas/mutasi'
    | '/keuangan/kas/rekonsiliasi'
    | '/keuangan/pembayaran/history'
    | '/keuangan/tabungan/$tabunganId'
    | '/keuangan/billing/'
    | '/keuangan/kas/'
    | '/keuangan/pembayaran/'
    | '/keuangan/tabungan/'
    | '/keuangan/billing/history/$periode'
    | '/keuangan/billing/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  KeuanganBillingRoute: typeof KeuanganBillingRouteWithChildren
  KeuanganKasRoute: typeof KeuanganKasRouteWithChildren
  KeuanganPembayaranRoute: typeof KeuanganPembayaranRouteWithChildren
  KeuanganTabunganRoute: typeof KeuanganTabunganRouteWithChildren
  MasterDiskonRoute: typeof MasterDiskonRoute
  MasterJenisPembayaranRoute: typeof MasterJenisPembayaranRoute
  MasterJenjangRoute: typeof MasterJenjangRoute
  MasterRombelRoute: typeof MasterRombelRoute
  MasterTahunAjaranRoute: typeof MasterTahunAjaranRoute
  SiswaProgresiRoute: typeof SiswaProgresiRoute
  SiswaIndexRoute: typeof SiswaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/': {
      id: '/siswa/'
      path: '/siswa'
      fullPath: '/siswa/'
      preLoaderRoute: typeof SiswaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/progresi': {
      id: '/siswa/progresi'
      path: '/siswa/progresi'
      fullPath: '/siswa/progresi'
      preLoaderRoute: typeof SiswaProgresiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/tahun-ajaran': {
      id: '/master/tahun-ajaran'
      path: '/master/tahun-ajaran'
      fullPath: '/master/tahun-ajaran'
      preLoaderRoute: typeof MasterTahunAjaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/rombel': {
      id: '/master/rombel'
      path: '/master/rombel'
      fullPath: '/master/rombel'
      preLoaderRoute: typeof MasterRombelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/jenjang': {
      id: '/master/jenjang'
      path: '/master/jenjang'
      fullPath: '/master/jenjang'
      preLoaderRoute: typeof MasterJenjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/jenis-pembayaran': {
      id: '/master/jenis-pembayaran'
      path: '/master/jenis-pembayaran'
      fullPath: '/master/jenis-pembayaran'
      preLoaderRoute: typeof MasterJenisPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/diskon': {
      id: '/master/diskon'
      path: '/master/diskon'
      fullPath: '/master/diskon'
      preLoaderRoute: typeof MasterDiskonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/tabungan': {
      id: '/keuangan/tabungan'
      path: '/keuangan/tabungan'
      fullPath: '/keuangan/tabungan'
      preLoaderRoute: typeof KeuanganTabunganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/pembayaran': {
      id: '/keuangan/pembayaran'
      path: '/keuangan/pembayaran'
      fullPath: '/keuangan/pembayaran'
      preLoaderRoute: typeof KeuanganPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/kas': {
      id: '/keuangan/kas'
      path: '/keuangan/kas'
      fullPath: '/keuangan/kas'
      preLoaderRoute: typeof KeuanganKasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/billing': {
      id: '/keuangan/billing'
      path: '/keuangan/billing'
      fullPath: '/keuangan/billing'
      preLoaderRoute: typeof KeuanganBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan/tabungan/': {
      id: '/keuangan/tabungan/'
      path: '/'
      fullPath: '/keuangan/tabungan/'
      preLoaderRoute: typeof KeuanganTabunganIndexRouteImport
      parentRoute: typeof KeuanganTabunganRoute
    }
    '/keuangan/pembayaran/': {
      id: '/keuangan/pembayaran/'
      path: '/'
      fullPath: '/keuangan/pembayaran/'
      preLoaderRoute: typeof KeuanganPembayaranIndexRouteImport
      parentRoute: typeof KeuanganPembayaranRoute
    }
    '/keuangan/kas/': {
      id: '/keuangan/kas/'
      path: '/'
      fullPath: '/keuangan/kas/'
      preLoaderRoute: typeof KeuanganKasIndexRouteImport
      parentRoute: typeof KeuanganKasRoute
    }
    '/keuangan/billing/': {
      id: '/keuangan/billing/'
      path: '/'
      fullPath: '/keuangan/billing/'
      preLoaderRoute: typeof KeuanganBillingIndexRouteImport
      parentRoute: typeof KeuanganBillingRoute
    }
    '/keuangan/tabungan/$tabunganId': {
      id: '/keuangan/tabungan/$tabunganId'
      path: '/$tabunganId'
      fullPath: '/keuangan/tabungan/$tabunganId'
      preLoaderRoute: typeof KeuanganTabunganTabunganIdRouteImport
      parentRoute: typeof KeuanganTabunganRoute
    }
    '/keuangan/pembayaran/history': {
      id: '/keuangan/pembayaran/history'
      path: '/history'
      fullPath: '/keuangan/pembayaran/history'
      preLoaderRoute: typeof KeuanganPembayaranHistoryRouteImport
      parentRoute: typeof KeuanganPembayaranRoute
    }
    '/keuangan/kas/rekonsiliasi': {
      id: '/keuangan/kas/rekonsiliasi'
      path: '/rekonsiliasi'
      fullPath: '/keuangan/kas/rekonsiliasi'
      preLoaderRoute: typeof KeuanganKasRekonsiliasiRouteImport
      parentRoute: typeof KeuanganKasRoute
    }
    '/keuangan/kas/mutasi': {
      id: '/keuangan/kas/mutasi'
      path: '/mutasi'
      fullPath: '/keuangan/kas/mutasi'
      preLoaderRoute: typeof KeuanganKasMutasiRouteImport
      parentRoute: typeof KeuanganKasRoute
    }
    '/keuangan/billing/history/': {
      id: '/keuangan/billing/history/'
      path: '/history'
      fullPath: '/keuangan/billing/history/'
      preLoaderRoute: typeof KeuanganBillingHistoryIndexRouteImport
      parentRoute: typeof KeuanganBillingRoute
    }
    '/keuangan/billing/history/$periode': {
      id: '/keuangan/billing/history/$periode'
      path: '/history/$periode'
      fullPath: '/keuangan/billing/history/$periode'
      preLoaderRoute: typeof KeuanganBillingHistoryPeriodeRouteImport
      parentRoute: typeof KeuanganBillingRoute
    }
  }
}

interface KeuanganBillingRouteChildren {
  KeuanganBillingIndexRoute: typeof KeuanganBillingIndexRoute
  KeuanganBillingHistoryPeriodeRoute: typeof KeuanganBillingHistoryPeriodeRoute
  KeuanganBillingHistoryIndexRoute: typeof KeuanganBillingHistoryIndexRoute
}

const KeuanganBillingRouteChildren: KeuanganBillingRouteChildren = {
  KeuanganBillingIndexRoute: KeuanganBillingIndexRoute,
  KeuanganBillingHistoryPeriodeRoute: KeuanganBillingHistoryPeriodeRoute,
  KeuanganBillingHistoryIndexRoute: KeuanganBillingHistoryIndexRoute,
}

const KeuanganBillingRouteWithChildren = KeuanganBillingRoute._addFileChildren(
  KeuanganBillingRouteChildren,
)

interface KeuanganKasRouteChildren {
  KeuanganKasMutasiRoute: typeof KeuanganKasMutasiRoute
  KeuanganKasRekonsiliasiRoute: typeof KeuanganKasRekonsiliasiRoute
  KeuanganKasIndexRoute: typeof KeuanganKasIndexRoute
}

const KeuanganKasRouteChildren: KeuanganKasRouteChildren = {
  KeuanganKasMutasiRoute: KeuanganKasMutasiRoute,
  KeuanganKasRekonsiliasiRoute: KeuanganKasRekonsiliasiRoute,
  KeuanganKasIndexRoute: KeuanganKasIndexRoute,
}

const KeuanganKasRouteWithChildren = KeuanganKasRoute._addFileChildren(
  KeuanganKasRouteChildren,
)

interface KeuanganPembayaranRouteChildren {
  KeuanganPembayaranHistoryRoute: typeof KeuanganPembayaranHistoryRoute
  KeuanganPembayaranIndexRoute: typeof KeuanganPembayaranIndexRoute
}

const KeuanganPembayaranRouteChildren: KeuanganPembayaranRouteChildren = {
  KeuanganPembayaranHistoryRoute: KeuanganPembayaranHistoryRoute,
  KeuanganPembayaranIndexRoute: KeuanganPembayaranIndexRoute,
}

const KeuanganPembayaranRouteWithChildren =
  KeuanganPembayaranRoute._addFileChildren(KeuanganPembayaranRouteChildren)

interface KeuanganTabunganRouteChildren {
  KeuanganTabunganTabunganIdRoute: typeof KeuanganTabunganTabunganIdRoute
  KeuanganTabunganIndexRoute: typeof KeuanganTabunganIndexRoute
}

const KeuanganTabunganRouteChildren: KeuanganTabunganRouteChildren = {
  KeuanganTabunganTabunganIdRoute: KeuanganTabunganTabunganIdRoute,
  KeuanganTabunganIndexRoute: KeuanganTabunganIndexRoute,
}

const KeuanganTabunganRouteWithChildren =
  KeuanganTabunganRoute._addFileChildren(KeuanganTabunganRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  KeuanganBillingRoute: KeuanganBillingRouteWithChildren,
  KeuanganKasRoute: KeuanganKasRouteWithChildren,
  KeuanganPembayaranRoute: KeuanganPembayaranRouteWithChildren,
  KeuanganTabunganRoute: KeuanganTabunganRouteWithChildren,
  MasterDiskonRoute: MasterDiskonRoute,
  MasterJenisPembayaranRoute: MasterJenisPembayaranRoute,
  MasterJenjangRoute: MasterJenjangRoute,
  MasterRombelRoute: MasterRombelRoute,
  MasterTahunAjaranRoute: MasterTahunAjaranRoute,
  SiswaProgresiRoute: SiswaProgresiRoute,
  SiswaIndexRoute: SiswaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
