/**
 * Custom hooks for preview-sync-invoices (dry-run sebelum sinkronisasi tagihan).
 * This is NOT auto-generated by Orval — a manual addition for the new endpoints.
 * Endpoint eksekusi (sync-invoices) memakai hook Orval yang sudah ada.
 */

import { customInstance } from "../../mutator/custom-instance";

// ─── Types (mengikuti DTO backend) ────────────────────────────────────────

export interface MonthYearBrief {
	month: number;
	year: number;
}

export interface ExtracurricularPreviewItem {
	student_id: number;
	student_name: string;
	extracurricular_id: number;
	extracurricular_name: string;
	months_to_add: MonthYearBrief[];
	skipped_excluded: number;
	skipped_exists: number;
	skipped_no_invoice: number;
}

export interface ExtracurricularPreviewResponse {
	total_enrollments: number;
	items: ExtracurricularPreviewItem[];
}

export interface DaycarePreviewItem {
	student_id: number;
	student_name: string;
	category: string; // premium | regular
	will_sync: boolean;
	reason: string;
}

export interface DaycarePreviewResponse {
	total_enrollments: number;
	items: DaycarePreviewItem[];
}

// ─── Cleanup preview PASTA (dry-run sebelum "Bersihkan tagihan PASTA") ───────

export interface ExtracurricularCleanupPreviewItem {
	invoice_id: number;
	month: number;
	year: number;
	item_id: number;
	item_name: string;
	/** "remove" = dihapus; "writeoff" = sisa dibebaskan (sudah dibayar sebagian). */
	action: string;
	amount: number;
}

export interface ExtracurricularCleanupPreviewResponse {
	student_id: number;
	extracurricular_id: number;
	extracurricular_name: string;
	start_date: string;
	total_items: number;
	total_amount: number;
	items: ExtracurricularCleanupPreviewItem[];
}

export interface ApiSuccessResponse<T> {
	data: { message: string; data: T };
	status: number;
	headers: Headers;
}

// ─── Preview endpoints ────────────────────────────────────────────────────

export const postV1ExtracurricularsPreviewSyncInvoices = async (
	options?: RequestInit,
): Promise<ApiSuccessResponse<ExtracurricularPreviewResponse>> => {
	return customInstance<ApiSuccessResponse<ExtracurricularPreviewResponse>>(
		"/v1/extracurriculars/preview-sync-invoices",
		{ ...options, method: "POST" },
	);
};

export const postV1DaycareEnrollmentsPreviewSyncInvoices = async (
	options?: RequestInit,
): Promise<ApiSuccessResponse<DaycarePreviewResponse>> => {
	return customInstance<ApiSuccessResponse<DaycarePreviewResponse>>(
		"/v1/daycare-enrollments/preview-sync-invoices",
		{ ...options, method: "POST" },
	);
};

export const postV1StudentsIdExtracurricularsCleanupInvoicesPreview = async (
	studentId: number,
	extracurricularId: number,
): Promise<ApiSuccessResponse<ExtracurricularCleanupPreviewResponse>> => {
	return customInstance<
		ApiSuccessResponse<ExtracurricularCleanupPreviewResponse>
	>(
		`/v1/students/${studentId}/extracurriculars/${extracurricularId}/cleanup-invoices/preview`,
		{ method: "POST" },
	);
};
