/**
 * Custom hook for updating invoice item quantity (override hari efektif per item).
 * This is NOT auto-generated by Orval — it's a manual addition for the new endpoint.
 */
import { useMutation } from '@tanstack/react-query';
import type { UseMutationOptions, QueryClient, UseMutationResult } from '@tanstack/react-query';
import { customInstance } from '../../mutator/custom-instance';

// Request type
export interface UpdateInvoiceItemQuantityRequest {
  quantity: number;
}

// Response wraps the standard success response
export interface UpdateInvoiceItemQuantityResponse {
  data: {
    message: string;
    data: {
      id: number;
      name: string;
      category: string;
      amount: number;
      paid_amount: number;
      status: string;
      is_mandatory: boolean;
      quantity?: number;
      unit_price?: number;
    };
  };
  status: number;
  headers: Headers;
}

export const putV1InvoicesIdItemsItemIdQuantity = async (
  invoiceId: number,
  itemId: number,
  data: UpdateInvoiceItemQuantityRequest,
  options?: RequestInit,
): Promise<UpdateInvoiceItemQuantityResponse> => {
  return customInstance<UpdateInvoiceItemQuantityResponse>(
    `/v1/invoices/${invoiceId}/items/${itemId}/quantity`,
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(data),
    },
  );
};

export const usePutV1InvoicesIdItemsItemIdQuantity = <
  TError = Error,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putV1InvoicesIdItemsItemIdQuantity>>,
      TError,
      { invoiceId: number; itemId: number; data: UpdateInvoiceItemQuantityRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putV1InvoicesIdItemsItemIdQuantity>>,
  TError,
  { invoiceId: number; itemId: number; data: UpdateInvoiceItemQuantityRequest },
  TContext
> => {
  const mutationFn = ({
    invoiceId,
    itemId,
    data,
  }: {
    invoiceId: number;
    itemId: number;
    data: UpdateInvoiceItemQuantityRequest;
  }) => putV1InvoicesIdItemsItemIdQuantity(invoiceId, itemId, data);

  return useMutation(
    { mutationFn, ...options?.mutation },
    queryClient,
  );
};
