/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type DtoCreateFeeConfigItemRequestUnit = typeof DtoCreateFeeConfigItemRequestUnit[keyof typeof DtoCreateFeeConfigItemRequestUnit];


export const DtoCreateFeeConfigItemRequestUnit = {
  fixed: 'fixed',
  per_day: 'per_day',
  per_monday: 'per_monday',
  percent: 'percent',
} as const;
