/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoClassChangeRequest {
  event_date: string;
  from_class_group_id: number;
  notes?: string;
  student_id: number;
  to_class_group_id: number;
}
