/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoCreateUserRequestRole } from "./dtoCreateUserRequestRole";

export interface DtoCreateUserRequest {
	email: string;
	/**
	 * @minLength 3
	 * @maxLength 100
	 */
	full_name: string;
	modules?: string[];
	/** @minLength 8 */
	password: string;
	role: DtoCreateUserRequestRole;
}
