/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoCreateDaycareEnrollmentRequestAgeGroup } from "./dtoCreateDaycareEnrollmentRequestAgeGroup";
import type { DtoCreateDaycareEnrollmentRequestCategory } from "./dtoCreateDaycareEnrollmentRequestCategory";
import type { DtoCreateDaycareEnrollmentRequestEnrollmentType } from "./dtoCreateDaycareEnrollmentRequestEnrollmentType";
import type { DtoCreateDaycareEnrollmentRequestTimeSlot } from "./dtoCreateDaycareEnrollmentRequestTimeSlot";

export interface DtoCreateDaycareEnrollmentRequest {
	academic_year_id: number;
	age_group: DtoCreateDaycareEnrollmentRequestAgeGroup;
	category: DtoCreateDaycareEnrollmentRequestCategory;
	/** hanya untuk premium */
	enrollment_type?: DtoCreateDaycareEnrollmentRequestEnrollmentType;
	start_date: string;
	student_id: number;
	time_slot: DtoCreateDaycareEnrollmentRequestTimeSlot;
}
