/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoClassGroupSchedule } from "./dtoClassGroupSchedule";

export interface DtoClassGroupResponse {
	academic_year_id?: number;
	id?: number;
	is_mutation?: boolean;
	level?: string;
	name?: string;
	schedule?: DtoClassGroupSchedule;
	student_count?: number;
}
