/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoCreatePaymentRequestSource } from './dtoCreatePaymentRequestSource';
import type { DtoPaymentItemReq } from './dtoPaymentItemReq';

export interface DtoCreatePaymentRequest {
  academic_year_id: number;
  items?: DtoPaymentItemReq[];
  notes?: string;
  payment_date: string;
  /** @minimum 0 */
  savings_deposit?: number;
  source: DtoCreatePaymentRequestSource;
  student_id: number;
}
