/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoCreateGuardianRequestRelationship } from './dtoCreateGuardianRequestRelationship';

export interface DtoCreateGuardianRequest {
  address?: string;
  /** @maxLength 100 */
  full_name: string;
  /** @maxLength 20 */
  phone: string;
  relationship: DtoCreateGuardianRequestRelationship;
}
