/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoCreateIncomeTransactionRequest {
	academic_year_id: number;
	/** @minimum 1 */
	amount: number;
	income_category_id: number;
	notes?: string;
	/** @maxLength 50 */
	reference_number?: string;
	/** @maxLength 100 */
	source_name: string;
	transaction_date: string;
}
