/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoCreateAcademicYearRequest {
  end_date: string;
  /** @maxLength 20 */
  name: string;
  start_date: string;
}
