/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type DtoCreateDaycareEnrollmentRequestCategory =
	(typeof DtoCreateDaycareEnrollmentRequestCategory)[keyof typeof DtoCreateDaycareEnrollmentRequestCategory];

export const DtoCreateDaycareEnrollmentRequestCategory = {
	premium: "premium",
	regular: "regular",
} as const;
