/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoClassGroupSchedule } from "./dtoClassGroupSchedule";
import type { DtoCreateClassGroupRequestLevel } from "./dtoCreateClassGroupRequestLevel";

export interface DtoCreateClassGroupRequest {
	academic_year_id: number;
	is_mutation?: boolean;
	level: DtoCreateClassGroupRequestLevel;
	/** @maxLength 50 */
	name: string;
	schedule: DtoClassGroupSchedule;
}
