/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoCreateInvoiceItemRequest } from "./dtoCreateInvoiceItemRequest";
import type { DtoCreateInvoiceRequestType } from "./dtoCreateInvoiceRequestType";

export interface DtoCreateInvoiceRequest {
	academic_year_id: number;
	due_date?: string;
	/** @minItems 1 */
	items: DtoCreateInvoiceItemRequest[];
	notes?: string;
	student_id: number;
	type: DtoCreateInvoiceRequestType;
}
