/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type DtoCreateDaycareEnrollmentRequestAgeGroup =
	(typeof DtoCreateDaycareEnrollmentRequestAgeGroup)[keyof typeof DtoCreateDaycareEnrollmentRequestAgeGroup];

export const DtoCreateDaycareEnrollmentRequestAgeGroup = {
	kbtk: "kbtk",
	under3: "under3",
} as const;
