/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoDaycareAttendanceResponse {
	date?: string;
	id?: number;
	student_id?: number;
	time_slot?: string;
}
