/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoDaycareSyncError } from "./dtoDaycareSyncError";

export interface DtoDaycareSyncResult {
	errors?: DtoDaycareSyncError[];
	total_enrollments?: number;
	total_skipped?: number;
	total_synced?: number;
}
