/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoAcademicYearBriefResponse } from "./dtoAcademicYearBriefResponse";
import type { DtoStudentBriefResponse } from "./dtoStudentBriefResponse";

export interface DtoDaycareEnrollmentResponse {
	academic_year?: DtoAcademicYearBriefResponse;
	age_group?: string;
	category?: string;
	end_date?: string;
	id?: number;
	package_type?: string;
	start_date?: string;
	status?: string;
	student?: DtoStudentBriefResponse;
	time_slot?: string;
}
