/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoCashSummaryResponse } from "./dtoCashSummaryResponse";
import type { DtoDailyClosingInReport } from "./dtoDailyClosingInReport";
import type { DtoExpenseSummaryResponse } from "./dtoExpenseSummaryResponse";
import type { DtoIncomeSummaryResponse } from "./dtoIncomeSummaryResponse";
import type { DtoVaultSummaryResponse } from "./dtoVaultSummaryResponse";

export interface DtoDailyReportResponse {
	academic_year?: string;
	cash?: DtoCashSummaryResponse;
	daily_closing?: DtoDailyClosingInReport;
	date?: string;
	expense_summary?: DtoExpenseSummaryResponse;
	income_summary?: DtoIncomeSummaryResponse;
	vault?: DtoVaultSummaryResponse;
}
