/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoExpenseCategoryResponse {
	children?: DtoExpenseCategoryResponse[];
	id?: number;
	invoice_category?: string;
	name?: string;
	parent_id?: number;
}
