/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoExtracurricularCleanupPreviewItem } from "./dtoExtracurricularCleanupPreviewItem";

export interface DtoExtracurricularCleanupPreviewResponse {
	extracurricular_id?: number;
	extracurricular_name?: string;
	items?: DtoExtracurricularCleanupPreviewItem[];
	start_date?: string;
	student_id?: number;
	total_amount?: number;
	total_items?: number;
}
