/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoClassGroupBriefResponse } from './dtoClassGroupBriefResponse';

export interface DtoEnrollmentBriefForStudent {
  class_group?: DtoClassGroupBriefResponse;
  class_group_id?: number;
}
