/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoEffectiveDayMonthCell } from "./dtoEffectiveDayMonthCell";

/**
 * nil = no override (follow level)
 */
export type DtoEffectiveDayClassGroupRowMonths = {
	[key: string]: DtoEffectiveDayMonthCell;
};
