/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoEnrollmentBriefResponse {
  academic_year_id?: number;
  academic_year_name?: string;
  class_group_id?: number;
  class_group_name?: string;
  id?: number;
  level?: string;
  start_date?: string;
  status?: string;
}
