/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoEnrollFacilityRequest {
	academic_year_id: number;
	facility_id: number;
	fee_config_item_id?: number;
	start_date: string;
}
