/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoAcademicYearBriefResponse } from './dtoAcademicYearBriefResponse';
import type { DtoFeeConfigItemResponse } from './dtoFeeConfigItemResponse';

export interface DtoFeeConfigResponse {
  academic_year?: DtoAcademicYearBriefResponse;
  created_at?: string;
  id?: number;
  items?: DtoFeeConfigItemResponse[];
  savings_admin_rate?: number;
}
