/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoFeeConfigItemResponse {
  amount?: number;
  category?: string;
  gender?: string;
  id?: number;
  item_key?: string;
  level?: string;
  name?: string;
  unit?: string;
}
