/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoFeeConfigItemBriefResponse } from "./dtoFeeConfigItemBriefResponse";
import type { DtoStudentBriefResponse } from "./dtoStudentBriefResponse";

export interface DtoFacilityStudentItemResponse {
	current_month_days?: number;
	end_date?: string;
	fee_config_item?: DtoFeeConfigItemBriefResponse;
	id?: number;
	start_date?: string;
	student?: DtoStudentBriefResponse;
}
