/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoGraduationStudentResult } from './dtoGraduationStudentResult';

export interface DtoGraduationResult {
  results?: DtoGraduationStudentResult[];
  total?: number;
}
