/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoGraduationStudentResult {
	graduation_amount?: number;
	graduation_invoice_id?: number;
	mandatory_savings_used?: number;
	remaining_debt?: number;
	student_id?: number;
	student_name?: string;
	surplus_returned_to_general?: number;
}
