/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoGenerateDaycareMonthlyRequest {
  academic_year_id: number;
  /**
     * @minimum 1
     * @maximum 12
     */
  month: number;
  student_id: number;
  year: number;
}
