/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoStudentBriefResponse } from './dtoStudentBriefResponse';

export interface DtoGuardianResponse {
  address?: string;
  full_name?: string;
  id?: number;
  phone?: string;
  relationship?: string;
  students?: DtoStudentBriefResponse[];
}
