/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoInvoiceItemResponse {
  amount?: number;
  category?: string;
  id?: number;
  is_koperasi?: boolean;
  is_mandatory?: boolean;
  koperasi_product_id?: number;
  koperasi_variant_id?: number;
  name?: string;
  paid_amount?: number;
  quantity?: number;
  status?: string;
  unit_price?: number;
}
