/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoClassArrearSummary } from "./dtoClassArrearSummary";
import type { DtoExpenseSummaryResponse } from "./dtoExpenseSummaryResponse";
import type { DtoMonthlyCashSummary } from "./dtoMonthlyCashSummary";
import type { DtoMonthlyIncomeSummary } from "./dtoMonthlyIncomeSummary";

export interface DtoMonthlyReportResponse {
	arrears_by_class?: DtoClassArrearSummary[];
	cash?: DtoMonthlyCashSummary;
	expense_summary?: DtoExpenseSummaryResponse;
	income_summary?: DtoMonthlyIncomeSummary;
	period?: string;
}
