/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoMeta } from "./dtoMeta";

export interface DtoPaginatedResponse {
	data?: unknown;
	message?: string;
	meta?: DtoMeta;
}
