/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoPromotionRequest {
	event_date: string;
	from_academic_year_id: number;
	notes?: string;
	retained_student_ids?: number[];
	to_academic_year_id: number;
}
