/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoSavingsMandatorySyncError } from "./dtoSavingsMandatorySyncError";

export interface DtoSavingsMandatorySyncResult {
	errors?: DtoSavingsMandatorySyncError[];
	total_invoices?: number;
	total_skipped?: number;
	total_students?: number;
	total_synced?: number;
}
