/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoUpsertDaycareAttendanceRequest {
  academic_year_id: number;
  date: string;
  student_id: number;
  /** empty = absent */
  time_slot?: string;
}
