/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoUpdateStudentRequestGender } from "./dtoUpdateStudentRequestGender";

export interface DtoUpdateStudentRequest {
	birth_date: string;
	/** @maxLength 100 */
	birth_place: string;
	/**
	 * @minLength 3
	 * @maxLength 100
	 */
	full_name: string;
	gender: DtoUpdateStudentRequestGender;
	is_daycare_only?: boolean;
	/** @maxLength 30 */
	religion?: string;
}
