/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoUpsertDaycareMonthlyAttendanceRequest {
	academic_year_id: number;
	/** @maximum 30 */
	meal_days?: number;
	/**
	 * @minimum 1
	 * @maximum 12
	 */
	month: number;
	/** @maximum 6000 (100 jam) */
	overtime_minutes?: number;
	/** @maximum 30 */
	spd_days?: number;
	student_id: number;
	year: number;
}
