/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1AuditLogsParams = {
	/**
	 * Search by path, error message, or user name
	 */
	search?: string;
	/**
	 * Filter by user ID
	 */
	user_id?: number;
	/**
	 * Filter by module (administrasi|keuangan|koperasi|laporan|pengaturan|auth)
	 */
	module?: string;
	/**
	 * Filter by HTTP method (POST|PUT|PATCH|DELETE)
	 */
	method?: string;
	/**
	 * Filter status >= N
	 */
	status_min?: number;
	/**
	 * Filter status <= N
	 */
	status_max?: number;
	/**
	 * Filter from date (YYYY-MM-DD)
	 */
	date_from?: string;
	/**
	 * Filter to date (YYYY-MM-DD)
	 */
	date_to?: string;
	/**
	 * Page number
	 */
	page?: number;
	/**
	 * Items per page
	 */
	limit?: number;
};
