/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1ExtracurricularsIdStudentsParams = {
	/**
	 * Academic Year ID
	 */
	academic_year_id: number;
	/**
	 * Bulan awal rentang (1-12); kosong = bulan pertama tahun ajaran
	 */
	month_from?: number;
	/**
	 * Tahun awal rentang; kosong = tahun mulai tahun ajaran
	 */
	year_from?: number;
	/**
	 * Bulan akhir rentang (1-12); kosong = bulan terakhir tahun ajaran
	 */
	month_to?: number;
	/**
	 * Tahun akhir rentang; kosong = tahun akhir tahun ajaran
	 */
	year_to?: number;
};
