/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1DaycareEnrollmentsParams = {
	/**
	 * Filter by status
	 */
	status?: string;
	/**
	 * Search by student name
	 */
	search?: string;
	/**
	 * Academic Year ID
	 */
	academic_year_id?: number;
	/**
	 * Page number
	 */
	page?: number;
	/**
	 * Items per page
	 */
	limit?: number;
};
