/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1PaymentsParams = {
	/**
	 * Page number
	 */
	page?: number;
	/**
	 * Limit per page
	 */
	limit?: number;
	/**
	 * Student ID
	 */
	student_id?: number;
	/**
	 * Academic Year ID
	 */
	academic_year_id?: number;
	/**
	 * Payment Source (cash/savings)
	 */
	source?: string;
	/**
	 * Start Date (YYYY-MM-DD)
	 */
	start_date?: string;
	/**
	 * End Date (YYYY-MM-DD)
	 */
	end_date?: string;
	/**
	 * Search by student name
	 */
	search?: string;
	/**
	 * Jenjang siswa (intan/berlian) via enrollment aktif
	 */
	level?: string;
	/**
	 * ID rombel siswa via enrollment aktif
	 */
	class_group_id?: number;
	/**
	 * Petugas pencatat (user ID)
	 */
	created_by?: number;
	/**
	 * Kategori item yang dibayar (monthly_spp, pasta, dll)
	 */
	category?: string;
	/**
	 * Periode tagihan yang dibayar (bulan 1-12)
	 */
	month?: number;
	/**
	 * Periode tagihan yang dibayar (tahun)
	 */
	year?: number;
};
