/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1DaycareEnrollmentsCheckPremiumHistoryParams = {
	/**
	 * Also delete unpaid invoices
	 */
	delete_invoices?: boolean;
	/**
	 * Student ID
	 */
	student_id: number;
};
