/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1UsersParams = {
/**
 * Search by name or email
 */
search?: string;
/**
 * Filter by role
 */
role?: string;
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
};
