/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1InvoicesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by student ID
 */
student_id?: number;
/**
 * Filter by academic year ID
 */
academic_year_id?: number;
/**
 * Filter by month (1-12)
 */
month?: number;
/**
 * Filter by year
 */
year?: number;
/**
 * Filter by class group ID
 */
class_group_id?: number;
/**
 * Filter by type
 */
type?: string;
/**
 * Filter by status
 */
status?: string;
};
