/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoIncomeTransactionResponse } from './dtoIncomeTransactionResponse';
import type { DtoSuccessResponse } from './dtoSuccessResponse';

export type GetV1IncomeTransactionsId200 = DtoSuccessResponse & {
  data?: DtoIncomeTransactionResponse;
};
