/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1ReportsMonthlyParams = {
/**
 * Month (1-12)
 */
month: number;
/**
 * Year
 */
year: number;
/**
 * Academic Year ID
 */
academic_year_id?: number;
};
