/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoPaginatedResponse } from './dtoPaginatedResponse';
import type { KasTransactionResponse } from './kasTransactionResponse';

export type GetV1KoperasiCashTransactions200 = DtoPaginatedResponse & {
  data?: KasTransactionResponse[];
};
