/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1ReportsPengeluaranParams = {
	/**
	 * Start date (YYYY-MM-DD)
	 */
	date_from: string;
	/**
	 * End date (YYYY-MM-DD)
	 */
	date_to: string;
	/**
	 * Comma-separated expense category IDs
	 */
	expense_category_ids?: string;
	/**
	 * Academic Year ID
	 */
	academic_year_id?: number;
};
