/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1KoperasiLoansParams = {
	/**
	 * Tahun ajaran
	 */
	academic_year_id?: number;
	/**
	 * Anggota
	 */
	member_id?: number;
	/**
	 * unpaid|partial|paid
	 */
	status?: string;
	/**
	 * Halaman
	 */
	page?: number;
	/**
	 * Per halaman
	 */
	limit?: number;
};
