/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1KoperasiReportsMonthlyParams = {
	/**
	 * Tahun ajaran
	 */
	academic_year_id?: number;
	/**
	 * Bulan (1-12)
	 */
	month?: number;
	/**
	 * Tahun
	 */
	year?: number;
};
