/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type GetV1ReportsTabunganParams = {
	/**
	 * Month (1-12)
	 */
	month: number;
	/**
	 * Year
	 */
	year: number;
	/**
	 * Savings type filter: general, mandatory, or empty for all
	 */
	type?: string;
};
