/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoDailyClosingListResponse } from "./dtoDailyClosingListResponse";
import type { DtoPaginatedResponse } from "./dtoPaginatedResponse";

export type GetV1DailyClosings200 = DtoPaginatedResponse & {
	data?: DtoDailyClosingListResponse[];
};
