/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { HandlerBatchEnrollRequestEnrollmentType } from "./handlerBatchEnrollRequestEnrollmentType";

export interface HandlerBatchEnrollRequest {
	academic_year_id: number;
	class_group_id: number;
	enrollment_type?: HandlerBatchEnrollRequestEnrollmentType;
	start_date: string;
	student_ids?: number[];
}
