/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { InternalModulesKoperasiLaporanCategoryLine } from './internalModulesKoperasiLaporanCategoryLine';

export interface InternalModulesKoperasiLaporanMonthlyReport {
  categories?: InternalModulesKoperasiLaporanCategoryLine[];
  month?: number;
  net?: number;
  total_credit?: number;
  total_debit?: number;
  year?: number;
}
