/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface InternalModulesKoperasiLaporanStockItem {
  cost_price?: number;
  name?: string;
  product_id?: number;
  sale_price?: number;
  stock?: number;
  stock_value?: number;
  variant_id?: number;
  variant_name?: string;
}
