/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { InternalModulesKoperasiPembelianCreateItemRequest } from "./internalModulesKoperasiPembelianCreateItemRequest";
import type { InternalModulesKoperasiPembelianCreateRequestPaymentMethod } from "./internalModulesKoperasiPembelianCreateRequestPaymentMethod";

export interface InternalModulesKoperasiPembelianCreateRequest {
	academic_year_id: number;
	/** @minimum 0 */
	initial_payment?: number;
	/** @minItems 1 */
	items: InternalModulesKoperasiPembelianCreateItemRequest[];
	notes?: string;
	payment_method?: InternalModulesKoperasiPembelianCreateRequestPaymentMethod;
	purchase_date: string;
	/** @maxLength 50 */
	reference_number?: string;
	supplier_id: number;
}
