/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { InternalModulesKoperasiLainlainCreateRequestFlow } from "./internalModulesKoperasiLainlainCreateRequestFlow";

export interface InternalModulesKoperasiLainlainCreateRequest {
	academic_year_id: number;
	amount: number;
	/** @maxLength 50 */
	category: string;
	description?: string;
	flow: InternalModulesKoperasiLainlainCreateRequestFlow;
	transaction_date: string;
}
