/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type InternalModulesKoperasiPinjamanCreateRequestRepaymentMethod = typeof InternalModulesKoperasiPinjamanCreateRequestRepaymentMethod[keyof typeof InternalModulesKoperasiPinjamanCreateRequestRepaymentMethod];


export const InternalModulesKoperasiPinjamanCreateRequestRepaymentMethod = {
  potong_gaji: 'potong_gaji',
  manual: 'manual',
} as const;
