/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface InternalModulesKoperasiAnggotaEmployeeResponse {
	full_name?: string;
	id?: number;
	is_active?: boolean;
	join_date?: string;
	legacy_id?: number;
}
