/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface InternalModulesKoperasiKasTransactionResponse {
	amount?: number;
	category?: string;
	created_by?: string;
	description?: string;
	id?: number;
	source_id?: number;
	source_type?: string;
	transaction_date?: string;
	transaction_type?: string;
}
