/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface LainlainResponse {
	academic_year_id?: number;
	amount?: number;
	category?: string;
	created_at?: string;
	created_by?: string;
	description?: string;
	flow?: string;
	id?: number;
	transaction_date?: string;
}
