/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { PembelianItemResponse } from "./pembelianItemResponse";

export interface PembelianResponse {
	academic_year_id?: number;
	created_at?: string;
	created_by?: string;
	id?: number;
	items?: PembelianItemResponse[];
	notes?: string;
	paid_amount?: number;
	purchase_date?: string;
	reference_number?: string;
	remaining?: number;
	status?: string;
	supplier_id?: number;
	supplier_name?: string;
	total_amount?: number;
}
