/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface PembelianItemResponse {
  product_id?: number;
  product_name?: string;
  quantity?: number;
  subtotal?: number;
  unit_price?: number;
  variant_id?: number;
  variant_name?: string;
}
