/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { PinjamanPaymentRequestMethod } from './pinjamanPaymentRequestMethod';

export interface PinjamanPaymentRequest {
  amount: number;
  method?: PinjamanPaymentRequestMethod;
  notes?: string;
  payment_date: string;
}
