/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type PinjamanPaymentRequestMethod = typeof PinjamanPaymentRequestMethod[keyof typeof PinjamanPaymentRequestMethod];


export const PinjamanPaymentRequestMethod = {
  cash: 'cash',
  potong_gaji: 'potong_gaji',
} as const;
