/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoExtracurricularSyncResult } from "./dtoExtracurricularSyncResult";
import type { DtoSuccessResponse } from "./dtoSuccessResponse";

export type PostV1ExtracurricularsSyncInvoices200 = DtoSuccessResponse & {
	data?: DtoExtracurricularSyncResult;
};
