/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoSuccessResponse } from "./dtoSuccessResponse";
import type { ServiceBackupResult } from "./serviceBackupResult";

export type PostV1Backups201 = DtoSuccessResponse & {
	data?: ServiceBackupResult;
};
