/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type PostV1BackupsParams = {
	/**
	 * Format backup: dump, sql, sql-compat
	 */
	format?: string;
};
