/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoDispensationResponse } from "./dtoDispensationResponse";
import type { DtoSuccessResponse } from "./dtoSuccessResponse";

export type PutV1DispensationsId200 = DtoSuccessResponse & {
	data?: DtoDispensationResponse;
};
