/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoPaymentDetailResponse } from "./dtoPaymentDetailResponse";
import type { DtoSuccessResponse } from "./dtoSuccessResponse";

export type PutV1PaymentsId200 = DtoSuccessResponse & {
	data?: DtoPaymentDetailResponse;
};
