/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoCreateExpenseRequest,
  DtoErrorResponse,
  DtoSuccessResponse,
  GetV1Expenses200,
  GetV1ExpensesId200,
  GetV1ExpensesParams,
  PostV1Expenses201,
  PutV1ExpensesId200
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1ExpensesResponse200 = {
  data: GetV1Expenses200
  status: 200
}

export type getV1ExpensesResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getV1ExpensesResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type getV1ExpensesResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type getV1ExpensesResponseSuccess = (getV1ExpensesResponse200) & {
  headers: Headers;
};
export type getV1ExpensesResponseError = (getV1ExpensesResponse401 | getV1ExpensesResponse403 | getV1ExpensesResponse500) & {
  headers: Headers;
};

export type getV1ExpensesResponse = (getV1ExpensesResponseSuccess | getV1ExpensesResponseError)

export const getGetV1ExpensesUrl = (params?: GetV1ExpensesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/expenses?${stringifiedParams}` : `/v1/expenses`
}

/**
 * Get a paginated list of expenses
 * @summary Get expense list
 */
export const getV1Expenses = async (params?: GetV1ExpensesParams, options?: RequestInit): Promise<getV1ExpensesResponse> => {

  return customInstance<getV1ExpensesResponse>(getGetV1ExpensesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ExpensesQueryKey = (params?: GetV1ExpensesParams,) => {
    return [
    `/v1/expenses`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1ExpensesQueryOptions = <TData = Awaited<ReturnType<typeof getV1Expenses>>, TError = DtoErrorResponse>(params?: GetV1ExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Expenses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ExpensesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Expenses>>> = ({ signal }) => getV1Expenses(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Expenses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ExpensesQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Expenses>>>
export type GetV1ExpensesQueryError = DtoErrorResponse


export function useGetV1Expenses<TData = Awaited<ReturnType<typeof getV1Expenses>>, TError = DtoErrorResponse>(
 params: undefined |  GetV1ExpensesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Expenses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Expenses>>,
          TError,
          Awaited<ReturnType<typeof getV1Expenses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Expenses<TData = Awaited<ReturnType<typeof getV1Expenses>>, TError = DtoErrorResponse>(
 params?: GetV1ExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Expenses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Expenses>>,
          TError,
          Awaited<ReturnType<typeof getV1Expenses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Expenses<TData = Awaited<ReturnType<typeof getV1Expenses>>, TError = DtoErrorResponse>(
 params?: GetV1ExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Expenses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get expense list
 */

export function useGetV1Expenses<TData = Awaited<ReturnType<typeof getV1Expenses>>, TError = DtoErrorResponse>(
 params?: GetV1ExpensesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Expenses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ExpensesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1ExpensesResponse201 = {
  data: PostV1Expenses201
  status: 201
}

export type postV1ExpensesResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postV1ExpensesResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postV1ExpensesResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type postV1ExpensesResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type postV1ExpensesResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type postV1ExpensesResponseSuccess = (postV1ExpensesResponse201) & {
  headers: Headers;
};
export type postV1ExpensesResponseError = (postV1ExpensesResponse400 | postV1ExpensesResponse401 | postV1ExpensesResponse403 | postV1ExpensesResponse422 | postV1ExpensesResponse500) & {
  headers: Headers;
};

export type postV1ExpensesResponse = (postV1ExpensesResponseSuccess | postV1ExpensesResponseError)

export const getPostV1ExpensesUrl = () => {




  return `/v1/expenses`
}

/**
 * Record a new expense
 * @summary Create expense
 */
export const postV1Expenses = async (dtoCreateExpenseRequest: DtoCreateExpenseRequest, options?: RequestInit): Promise<postV1ExpensesResponse> => {

  return customInstance<postV1ExpensesResponse>(getPostV1ExpensesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCreateExpenseRequest,)
  }
);}




export const getPostV1ExpensesMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Expenses>>, TError,{data: DtoCreateExpenseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1Expenses>>, TError,{data: DtoCreateExpenseRequest}, TContext> => {

const mutationKey = ['postV1Expenses'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Expenses>>, {data: DtoCreateExpenseRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1Expenses(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ExpensesMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Expenses>>>
    export type PostV1ExpensesMutationBody = DtoCreateExpenseRequest
    export type PostV1ExpensesMutationError = DtoErrorResponse

    /**
 * @summary Create expense
 */
export const usePostV1Expenses = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Expenses>>, TError,{data: DtoCreateExpenseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1Expenses>>,
        TError,
        {data: DtoCreateExpenseRequest},
        TContext
      > => {
      return useMutation(getPostV1ExpensesMutationOptions(options), queryClient);
    }
    export type getV1ExpensesIdResponse200 = {
  data: GetV1ExpensesId200
  status: 200
}

export type getV1ExpensesIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getV1ExpensesIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getV1ExpensesIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type getV1ExpensesIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getV1ExpensesIdResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type getV1ExpensesIdResponseSuccess = (getV1ExpensesIdResponse200) & {
  headers: Headers;
};
export type getV1ExpensesIdResponseError = (getV1ExpensesIdResponse400 | getV1ExpensesIdResponse401 | getV1ExpensesIdResponse403 | getV1ExpensesIdResponse404 | getV1ExpensesIdResponse500) & {
  headers: Headers;
};

export type getV1ExpensesIdResponse = (getV1ExpensesIdResponseSuccess | getV1ExpensesIdResponseError)

export const getGetV1ExpensesIdUrl = (id: number,) => {




  return `/v1/expenses/${id}`
}

/**
 * Get expense detail by ID
 * @summary Get expense by ID
 */
export const getV1ExpensesId = async (id: number, options?: RequestInit): Promise<getV1ExpensesIdResponse> => {

  return customInstance<getV1ExpensesIdResponse>(getGetV1ExpensesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ExpensesIdQueryKey = (id: number,) => {
    return [
    `/v1/expenses/${id}`
    ] as const;
    }


export const getGetV1ExpensesIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1ExpensesId>>, TError = DtoErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ExpensesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ExpensesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1ExpensesId>>> = ({ signal }) => getV1ExpensesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1ExpensesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ExpensesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1ExpensesId>>>
export type GetV1ExpensesIdQueryError = DtoErrorResponse


export function useGetV1ExpensesId<TData = Awaited<ReturnType<typeof getV1ExpensesId>>, TError = DtoErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ExpensesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ExpensesId>>,
          TError,
          Awaited<ReturnType<typeof getV1ExpensesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ExpensesId<TData = Awaited<ReturnType<typeof getV1ExpensesId>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ExpensesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ExpensesId>>,
          TError,
          Awaited<ReturnType<typeof getV1ExpensesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ExpensesId<TData = Awaited<ReturnType<typeof getV1ExpensesId>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ExpensesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get expense by ID
 */

export function useGetV1ExpensesId<TData = Awaited<ReturnType<typeof getV1ExpensesId>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ExpensesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ExpensesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type putV1ExpensesIdResponse200 = {
  data: PutV1ExpensesId200
  status: 200
}

export type putV1ExpensesIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putV1ExpensesIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putV1ExpensesIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putV1ExpensesIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putV1ExpensesIdResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type putV1ExpensesIdResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type putV1ExpensesIdResponseSuccess = (putV1ExpensesIdResponse200) & {
  headers: Headers;
};
export type putV1ExpensesIdResponseError = (putV1ExpensesIdResponse400 | putV1ExpensesIdResponse401 | putV1ExpensesIdResponse403 | putV1ExpensesIdResponse404 | putV1ExpensesIdResponse422 | putV1ExpensesIdResponse500) & {
  headers: Headers;
};

export type putV1ExpensesIdResponse = (putV1ExpensesIdResponseSuccess | putV1ExpensesIdResponseError)

export const getPutV1ExpensesIdUrl = (id: number,) => {




  return `/v1/expenses/${id}`
}

/**
 * Update an existing expense
 * @summary Update expense
 */
export const putV1ExpensesId = async (id: number,
    dtoCreateExpenseRequest: DtoCreateExpenseRequest, options?: RequestInit): Promise<putV1ExpensesIdResponse> => {

  return customInstance<putV1ExpensesIdResponse>(getPutV1ExpensesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCreateExpenseRequest,)
  }
);}




export const getPutV1ExpensesIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putV1ExpensesId>>, TError,{id: number;data: DtoCreateExpenseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putV1ExpensesId>>, TError,{id: number;data: DtoCreateExpenseRequest}, TContext> => {

const mutationKey = ['putV1ExpensesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putV1ExpensesId>>, {id: number;data: DtoCreateExpenseRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putV1ExpensesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutV1ExpensesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putV1ExpensesId>>>
    export type PutV1ExpensesIdMutationBody = DtoCreateExpenseRequest
    export type PutV1ExpensesIdMutationError = DtoErrorResponse

    /**
 * @summary Update expense
 */
export const usePutV1ExpensesId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putV1ExpensesId>>, TError,{id: number;data: DtoCreateExpenseRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putV1ExpensesId>>,
        TError,
        {id: number;data: DtoCreateExpenseRequest},
        TContext
      > => {
      return useMutation(getPutV1ExpensesIdMutationOptions(options), queryClient);
    }
    export type deleteV1ExpensesIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type deleteV1ExpensesIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type deleteV1ExpensesIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type deleteV1ExpensesIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type deleteV1ExpensesIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type deleteV1ExpensesIdResponse422 = {
  data: DtoErrorResponse
  status: 422
}

export type deleteV1ExpensesIdResponse500 = {
  data: DtoErrorResponse
  status: 500
}

export type deleteV1ExpensesIdResponseSuccess = (deleteV1ExpensesIdResponse200) & {
  headers: Headers;
};
export type deleteV1ExpensesIdResponseError = (deleteV1ExpensesIdResponse400 | deleteV1ExpensesIdResponse401 | deleteV1ExpensesIdResponse403 | deleteV1ExpensesIdResponse404 | deleteV1ExpensesIdResponse422 | deleteV1ExpensesIdResponse500) & {
  headers: Headers;
};

export type deleteV1ExpensesIdResponse = (deleteV1ExpensesIdResponseSuccess | deleteV1ExpensesIdResponseError)

export const getDeleteV1ExpensesIdUrl = (id: number,) => {




  return `/v1/expenses/${id}`
}

/**
 * Delete an existing expense
 * @summary Delete expense
 */
export const deleteV1ExpensesId = async (id: number, options?: RequestInit): Promise<deleteV1ExpensesIdResponse> => {

  return customInstance<deleteV1ExpensesIdResponse>(getDeleteV1ExpensesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1ExpensesIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1ExpensesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1ExpensesId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteV1ExpensesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1ExpensesId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteV1ExpensesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1ExpensesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1ExpensesId>>>

    export type DeleteV1ExpensesIdMutationError = DtoErrorResponse

    /**
 * @summary Delete expense
 */
export const useDeleteV1ExpensesId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1ExpensesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1ExpensesId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteV1ExpensesIdMutationOptions(options), queryClient);
    }
