/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	DtoErrorResponse,
	DtoSetBillingExclusionsRequest,
	GetV1StudentsIdFacilitiesFacilityIdBillingExclusions200,
	PutV1StudentsIdFacilitiesFacilityIdBillingExclusions200,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse200 = {
	data: GetV1StudentsIdFacilitiesFacilityIdBillingExclusions200;
	status: 200;
};

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse400 = {
	data: DtoErrorResponse;
	status: 400;
};

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse404 = {
	data: DtoErrorResponse;
	status: 404;
};

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseSuccess =
	getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse200 & {
		headers: Headers;
	};
export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseError =
	(
		| getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse400
		| getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse401
		| getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse403
		| getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse404
		| getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse500
	) & {
		headers: Headers;
	};

export type getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse =
	| getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseSuccess
	| getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseError;

export const getGetV1StudentsIdFacilitiesFacilityIdBillingExclusionsUrl = (
	id: number,
	facilityId: number,
) => {
	return `/v1/students/${id}/facilities/${facilityId}/billing-exclusions`;
};

/**
 * Daftar bulan yang tagihan fasilitas-nya di-skip
 * @summary Get billing month exclusions for a student facility
 */
export const getV1StudentsIdFacilitiesFacilityIdBillingExclusions = async (
	id: number,
	facilityId: number,
	options?: RequestInit,
): Promise<getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse> => {
	return customInstance<getV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse>(
		getGetV1StudentsIdFacilitiesFacilityIdBillingExclusionsUrl(id, facilityId),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetV1StudentsIdFacilitiesFacilityIdBillingExclusionsQueryKey = (
	id: number,
	facilityId: number,
) => {
	return [
		`/v1/students/${id}/facilities/${facilityId}/billing-exclusions`,
	] as const;
};

export const getGetV1StudentsIdFacilitiesFacilityIdBillingExclusionsQueryOptions =
	<
		TData = Awaited<
			ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
		>,
		TError = DtoErrorResponse,
	>(
		id: number,
		facilityId: number,
		options?: {
			query?: Partial<
				UseQueryOptions<
					Awaited<
						ReturnType<
							typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
						>
					>,
					TError,
					TData
				>
			>;
			request?: SecondParameter<typeof customInstance>;
		},
	) => {
		const { query: queryOptions, request: requestOptions } = options ?? {};

		const queryKey =
			queryOptions?.queryKey ??
			getGetV1StudentsIdFacilitiesFacilityIdBillingExclusionsQueryKey(
				id,
				facilityId,
			);

		const queryFn: QueryFunction<
			Awaited<
				ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
			>
		> = ({ signal }) =>
			getV1StudentsIdFacilitiesFacilityIdBillingExclusions(id, facilityId, {
				signal,
				...requestOptions,
			});

		return {
			queryKey,
			queryFn,
			enabled: !!(id && facilityId),
			...queryOptions,
		} as UseQueryOptions<
			Awaited<
				ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
			>,
			TError,
			TData
		> & { queryKey: DataTag<QueryKey, TData, TError> };
	};

export type GetV1StudentsIdFacilitiesFacilityIdBillingExclusionsQueryResult =
	NonNullable<
		Awaited<
			ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
		>
	>;
export type GetV1StudentsIdFacilitiesFacilityIdBillingExclusionsQueryError =
	DtoErrorResponse;

export function useGetV1StudentsIdFacilitiesFacilityIdBillingExclusions<
	TData = Awaited<
		ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
	>,
	TError = DtoErrorResponse,
>(
	id: number,
	facilityId: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
					>
				>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<
						ReturnType<
							typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
						>
					>,
					TError,
					Awaited<
						ReturnType<
							typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
						>
					>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1StudentsIdFacilitiesFacilityIdBillingExclusions<
	TData = Awaited<
		ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
	>,
	TError = DtoErrorResponse,
>(
	id: number,
	facilityId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
					>
				>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<
						ReturnType<
							typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
						>
					>,
					TError,
					Awaited<
						ReturnType<
							typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
						>
					>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1StudentsIdFacilitiesFacilityIdBillingExclusions<
	TData = Awaited<
		ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
	>,
	TError = DtoErrorResponse,
>(
	id: number,
	facilityId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
					>
				>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get billing month exclusions for a student facility
 */

export function useGetV1StudentsIdFacilitiesFacilityIdBillingExclusions<
	TData = Awaited<
		ReturnType<typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions>
	>,
	TError = DtoErrorResponse,
>(
	id: number,
	facilityId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getV1StudentsIdFacilitiesFacilityIdBillingExclusions
					>
				>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getGetV1StudentsIdFacilitiesFacilityIdBillingExclusionsQueryOptions(
			id,
			facilityId,
			options,
		);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse200 = {
	data: PutV1StudentsIdFacilitiesFacilityIdBillingExclusions200;
	status: 200;
};

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse400 = {
	data: DtoErrorResponse;
	status: 400;
};

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse404 = {
	data: DtoErrorResponse;
	status: 404;
};

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseSuccess =
	putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse200 & {
		headers: Headers;
	};
export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseError =
	(
		| putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse400
		| putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse401
		| putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse403
		| putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse404
		| putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse500
	) & {
		headers: Headers;
	};

export type putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse =
	| putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseSuccess
	| putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponseError;

export const getPutV1StudentsIdFacilitiesFacilityIdBillingExclusionsUrl = (
	id: number,
	facilityId: number,
) => {
	return `/v1/students/${id}/facilities/${facilityId}/billing-exclusions`;
};

/**
 * Ganti seluruh daftar bulan yang tagihan fasilitas-nya di-skip
 * @summary Set billing month exclusions for a student facility
 */
export const putV1StudentsIdFacilitiesFacilityIdBillingExclusions = async (
	id: number,
	facilityId: number,
	dtoSetBillingExclusionsRequest: DtoSetBillingExclusionsRequest,
	options?: RequestInit,
): Promise<putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse> => {
	return customInstance<putV1StudentsIdFacilitiesFacilityIdBillingExclusionsResponse>(
		getPutV1StudentsIdFacilitiesFacilityIdBillingExclusionsUrl(id, facilityId),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(dtoSetBillingExclusionsRequest),
		},
	);
};

export const getPutV1StudentsIdFacilitiesFacilityIdBillingExclusionsMutationOptions =
	<TError = DtoErrorResponse, TContext = unknown>(options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<typeof putV1StudentsIdFacilitiesFacilityIdBillingExclusions>
			>,
			TError,
			{ id: number; facilityId: number; data: DtoSetBillingExclusionsRequest },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	}): UseMutationOptions<
		Awaited<
			ReturnType<typeof putV1StudentsIdFacilitiesFacilityIdBillingExclusions>
		>,
		TError,
		{ id: number; facilityId: number; data: DtoSetBillingExclusionsRequest },
		TContext
	> => {
		const mutationKey = [
			"putV1StudentsIdFacilitiesFacilityIdBillingExclusions",
		];
		const { mutation: mutationOptions, request: requestOptions } = options
			? options.mutation &&
				"mutationKey" in options.mutation &&
				options.mutation.mutationKey
				? options
				: { ...options, mutation: { ...options.mutation, mutationKey } }
			: { mutation: { mutationKey }, request: undefined };

		const mutationFn: MutationFunction<
			Awaited<
				ReturnType<typeof putV1StudentsIdFacilitiesFacilityIdBillingExclusions>
			>,
			{ id: number; facilityId: number; data: DtoSetBillingExclusionsRequest }
		> = (props) => {
			const { id, facilityId, data } = props ?? {};

			return putV1StudentsIdFacilitiesFacilityIdBillingExclusions(
				id,
				facilityId,
				data,
				requestOptions,
			);
		};

		return { mutationFn, ...mutationOptions };
	};

export type PutV1StudentsIdFacilitiesFacilityIdBillingExclusionsMutationResult =
	NonNullable<
		Awaited<
			ReturnType<typeof putV1StudentsIdFacilitiesFacilityIdBillingExclusions>
		>
	>;
export type PutV1StudentsIdFacilitiesFacilityIdBillingExclusionsMutationBody =
	DtoSetBillingExclusionsRequest;
export type PutV1StudentsIdFacilitiesFacilityIdBillingExclusionsMutationError =
	DtoErrorResponse;

/**
 * @summary Set billing month exclusions for a student facility
 */
export const usePutV1StudentsIdFacilitiesFacilityIdBillingExclusions = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<typeof putV1StudentsIdFacilitiesFacilityIdBillingExclusions>
			>,
			TError,
			{ id: number; facilityId: number; data: DtoSetBillingExclusionsRequest },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<
		ReturnType<typeof putV1StudentsIdFacilitiesFacilityIdBillingExclusions>
	>,
	TError,
	{ id: number; facilityId: number; data: DtoSetBillingExclusionsRequest },
	TContext
> => {
	return useMutation(
		getPutV1StudentsIdFacilitiesFacilityIdBillingExclusionsMutationOptions(
			options,
		),
		queryClient,
	);
};
