/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	DtoCreateIncomeCategoryRequest,
	DtoErrorResponse,
	DtoSuccessResponse,
	GetV1IncomeCategories200,
	PostV1IncomeCategories201,
	PutV1IncomeCategoriesId200,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getV1IncomeCategoriesResponse200 = {
	data: GetV1IncomeCategories200;
	status: 200;
};

export type getV1IncomeCategoriesResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type getV1IncomeCategoriesResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type getV1IncomeCategoriesResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type getV1IncomeCategoriesResponseSuccess =
	getV1IncomeCategoriesResponse200 & {
		headers: Headers;
	};
export type getV1IncomeCategoriesResponseError = (
	| getV1IncomeCategoriesResponse401
	| getV1IncomeCategoriesResponse403
	| getV1IncomeCategoriesResponse500
) & {
	headers: Headers;
};

export type getV1IncomeCategoriesResponse =
	| getV1IncomeCategoriesResponseSuccess
	| getV1IncomeCategoriesResponseError;

export const getGetV1IncomeCategoriesUrl = () => {
	return `/v1/income-categories`;
};

/**
 * Get all income categories (flat list)
 * @summary Get income category list
 */
export const getV1IncomeCategories = async (
	options?: RequestInit,
): Promise<getV1IncomeCategoriesResponse> => {
	return customInstance<getV1IncomeCategoriesResponse>(
		getGetV1IncomeCategoriesUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetV1IncomeCategoriesQueryKey = () => {
	return [`/v1/income-categories`] as const;
};

export const getGetV1IncomeCategoriesQueryOptions = <
	TData = Awaited<ReturnType<typeof getV1IncomeCategories>>,
	TError = DtoErrorResponse,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getV1IncomeCategories>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetV1IncomeCategoriesQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getV1IncomeCategories>>
	> = ({ signal }) => getV1IncomeCategories({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getV1IncomeCategories>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1IncomeCategoriesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getV1IncomeCategories>>
>;
export type GetV1IncomeCategoriesQueryError = DtoErrorResponse;

export function useGetV1IncomeCategories<
	TData = Awaited<ReturnType<typeof getV1IncomeCategories>>,
	TError = DtoErrorResponse,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1IncomeCategories>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1IncomeCategories>>,
					TError,
					Awaited<ReturnType<typeof getV1IncomeCategories>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1IncomeCategories<
	TData = Awaited<ReturnType<typeof getV1IncomeCategories>>,
	TError = DtoErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1IncomeCategories>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1IncomeCategories>>,
					TError,
					Awaited<ReturnType<typeof getV1IncomeCategories>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1IncomeCategories<
	TData = Awaited<ReturnType<typeof getV1IncomeCategories>>,
	TError = DtoErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1IncomeCategories>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get income category list
 */

export function useGetV1IncomeCategories<
	TData = Awaited<ReturnType<typeof getV1IncomeCategories>>,
	TError = DtoErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1IncomeCategories>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetV1IncomeCategoriesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type postV1IncomeCategoriesResponse201 = {
	data: PostV1IncomeCategories201;
	status: 201;
};

export type postV1IncomeCategoriesResponse400 = {
	data: DtoErrorResponse;
	status: 400;
};

export type postV1IncomeCategoriesResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type postV1IncomeCategoriesResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type postV1IncomeCategoriesResponse422 = {
	data: DtoErrorResponse;
	status: 422;
};

export type postV1IncomeCategoriesResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type postV1IncomeCategoriesResponseSuccess =
	postV1IncomeCategoriesResponse201 & {
		headers: Headers;
	};
export type postV1IncomeCategoriesResponseError = (
	| postV1IncomeCategoriesResponse400
	| postV1IncomeCategoriesResponse401
	| postV1IncomeCategoriesResponse403
	| postV1IncomeCategoriesResponse422
	| postV1IncomeCategoriesResponse500
) & {
	headers: Headers;
};

export type postV1IncomeCategoriesResponse =
	| postV1IncomeCategoriesResponseSuccess
	| postV1IncomeCategoriesResponseError;

export const getPostV1IncomeCategoriesUrl = () => {
	return `/v1/income-categories`;
};

/**
 * Create a new income category
 * @summary Create income category
 */
export const postV1IncomeCategories = async (
	dtoCreateIncomeCategoryRequest: DtoCreateIncomeCategoryRequest,
	options?: RequestInit,
): Promise<postV1IncomeCategoriesResponse> => {
	return customInstance<postV1IncomeCategoriesResponse>(
		getPostV1IncomeCategoriesUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(dtoCreateIncomeCategoryRequest),
		},
	);
};

export const getPostV1IncomeCategoriesMutationOptions = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postV1IncomeCategories>>,
		TError,
		{ data: DtoCreateIncomeCategoryRequest },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postV1IncomeCategories>>,
	TError,
	{ data: DtoCreateIncomeCategoryRequest },
	TContext
> => {
	const mutationKey = ["postV1IncomeCategories"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postV1IncomeCategories>>,
		{ data: DtoCreateIncomeCategoryRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postV1IncomeCategories(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostV1IncomeCategoriesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postV1IncomeCategories>>
>;
export type PostV1IncomeCategoriesMutationBody = DtoCreateIncomeCategoryRequest;
export type PostV1IncomeCategoriesMutationError = DtoErrorResponse;

/**
 * @summary Create income category
 */
export const usePostV1IncomeCategories = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postV1IncomeCategories>>,
			TError,
			{ data: DtoCreateIncomeCategoryRequest },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postV1IncomeCategories>>,
	TError,
	{ data: DtoCreateIncomeCategoryRequest },
	TContext
> => {
	return useMutation(
		getPostV1IncomeCategoriesMutationOptions(options),
		queryClient,
	);
};
export type putV1IncomeCategoriesIdResponse200 = {
	data: PutV1IncomeCategoriesId200;
	status: 200;
};

export type putV1IncomeCategoriesIdResponse400 = {
	data: DtoErrorResponse;
	status: 400;
};

export type putV1IncomeCategoriesIdResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type putV1IncomeCategoriesIdResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type putV1IncomeCategoriesIdResponse404 = {
	data: DtoErrorResponse;
	status: 404;
};

export type putV1IncomeCategoriesIdResponse422 = {
	data: DtoErrorResponse;
	status: 422;
};

export type putV1IncomeCategoriesIdResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type putV1IncomeCategoriesIdResponseSuccess =
	putV1IncomeCategoriesIdResponse200 & {
		headers: Headers;
	};
export type putV1IncomeCategoriesIdResponseError = (
	| putV1IncomeCategoriesIdResponse400
	| putV1IncomeCategoriesIdResponse401
	| putV1IncomeCategoriesIdResponse403
	| putV1IncomeCategoriesIdResponse404
	| putV1IncomeCategoriesIdResponse422
	| putV1IncomeCategoriesIdResponse500
) & {
	headers: Headers;
};

export type putV1IncomeCategoriesIdResponse =
	| putV1IncomeCategoriesIdResponseSuccess
	| putV1IncomeCategoriesIdResponseError;

export const getPutV1IncomeCategoriesIdUrl = (id: number) => {
	return `/v1/income-categories/${id}`;
};

/**
 * Update an existing income category
 * @summary Update income category
 */
export const putV1IncomeCategoriesId = async (
	id: number,
	dtoCreateIncomeCategoryRequest: DtoCreateIncomeCategoryRequest,
	options?: RequestInit,
): Promise<putV1IncomeCategoriesIdResponse> => {
	return customInstance<putV1IncomeCategoriesIdResponse>(
		getPutV1IncomeCategoriesIdUrl(id),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(dtoCreateIncomeCategoryRequest),
		},
	);
};

export const getPutV1IncomeCategoriesIdMutationOptions = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putV1IncomeCategoriesId>>,
		TError,
		{ id: number; data: DtoCreateIncomeCategoryRequest },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putV1IncomeCategoriesId>>,
	TError,
	{ id: number; data: DtoCreateIncomeCategoryRequest },
	TContext
> => {
	const mutationKey = ["putV1IncomeCategoriesId"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putV1IncomeCategoriesId>>,
		{ id: number; data: DtoCreateIncomeCategoryRequest }
	> = (props) => {
		const { id, data } = props ?? {};

		return putV1IncomeCategoriesId(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutV1IncomeCategoriesIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putV1IncomeCategoriesId>>
>;
export type PutV1IncomeCategoriesIdMutationBody =
	DtoCreateIncomeCategoryRequest;
export type PutV1IncomeCategoriesIdMutationError = DtoErrorResponse;

/**
 * @summary Update income category
 */
export const usePutV1IncomeCategoriesId = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putV1IncomeCategoriesId>>,
			TError,
			{ id: number; data: DtoCreateIncomeCategoryRequest },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putV1IncomeCategoriesId>>,
	TError,
	{ id: number; data: DtoCreateIncomeCategoryRequest },
	TContext
> => {
	return useMutation(
		getPutV1IncomeCategoriesIdMutationOptions(options),
		queryClient,
	);
};
export type deleteV1IncomeCategoriesIdResponse200 = {
	data: DtoSuccessResponse;
	status: 200;
};

export type deleteV1IncomeCategoriesIdResponse400 = {
	data: DtoErrorResponse;
	status: 400;
};

export type deleteV1IncomeCategoriesIdResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type deleteV1IncomeCategoriesIdResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type deleteV1IncomeCategoriesIdResponse404 = {
	data: DtoErrorResponse;
	status: 404;
};

export type deleteV1IncomeCategoriesIdResponse422 = {
	data: DtoErrorResponse;
	status: 422;
};

export type deleteV1IncomeCategoriesIdResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type deleteV1IncomeCategoriesIdResponseSuccess =
	deleteV1IncomeCategoriesIdResponse200 & {
		headers: Headers;
	};
export type deleteV1IncomeCategoriesIdResponseError = (
	| deleteV1IncomeCategoriesIdResponse400
	| deleteV1IncomeCategoriesIdResponse401
	| deleteV1IncomeCategoriesIdResponse403
	| deleteV1IncomeCategoriesIdResponse404
	| deleteV1IncomeCategoriesIdResponse422
	| deleteV1IncomeCategoriesIdResponse500
) & {
	headers: Headers;
};

export type deleteV1IncomeCategoriesIdResponse =
	| deleteV1IncomeCategoriesIdResponseSuccess
	| deleteV1IncomeCategoriesIdResponseError;

export const getDeleteV1IncomeCategoriesIdUrl = (id: number) => {
	return `/v1/income-categories/${id}`;
};

/**
 * Delete an existing income category (only if no transactions use it)
 * @summary Delete income category
 */
export const deleteV1IncomeCategoriesId = async (
	id: number,
	options?: RequestInit,
): Promise<deleteV1IncomeCategoriesIdResponse> => {
	return customInstance<deleteV1IncomeCategoriesIdResponse>(
		getDeleteV1IncomeCategoriesIdUrl(id),
		{
			...options,
			method: "DELETE",
		},
	);
};

export const getDeleteV1IncomeCategoriesIdMutationOptions = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteV1IncomeCategoriesId>>,
		TError,
		{ id: number },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteV1IncomeCategoriesId>>,
	TError,
	{ id: number },
	TContext
> => {
	const mutationKey = ["deleteV1IncomeCategoriesId"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteV1IncomeCategoriesId>>,
		{ id: number }
	> = (props) => {
		const { id } = props ?? {};

		return deleteV1IncomeCategoriesId(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteV1IncomeCategoriesIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteV1IncomeCategoriesId>>
>;

export type DeleteV1IncomeCategoriesIdMutationError = DtoErrorResponse;

/**
 * @summary Delete income category
 */
export const useDeleteV1IncomeCategoriesId = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteV1IncomeCategoriesId>>,
			TError,
			{ id: number },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteV1IncomeCategoriesId>>,
	TError,
	{ id: number },
	TContext
> => {
	return useMutation(
		getDeleteV1IncomeCategoriesIdMutationOptions(options),
		queryClient,
	);
};
