/**
 * Custom hooks for income transactions (Dana Bantuan: BOS, Donasi, Hibah).
 * Manual implementation — not auto-generated by Orval.
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  UseMutationOptions,
  UseQueryOptions,
  QueryClient,
} from '@tanstack/react-query';
import { customInstance } from '../../mutator/custom-instance';

// ─── Types ───────────────────────────────────────────────────────────

export interface IncomeTransactionResponse {
  id: number;
  academic_year: { id: number; name: string };
  category: string;
  source_name: string;
  amount: number;
  transaction_date: string;
  reference_number?: string;
  notes?: string;
  created_by: { id: number; full_name: string };
  created_at: string;
}

export interface CreateIncomeTransactionRequest {
  academic_year_id: number;
  category: string;
  source_name: string;
  amount: number;
  transaction_date: string;
  reference_number?: string;
  notes?: string;
}

interface ListParams {
  page?: number;
  limit?: number;
  academic_year_id?: number;
  category?: string;
  start_date?: string;
  end_date?: string;
}

// ─── API Functions ───────────────────────────────────────────────────

const getIncomeTransactions = async (params?: ListParams) => {
  return customInstance<any>('/v1/income-transactions', {
    method: 'GET',
    params: params as Record<string, unknown>,
  });
};

const getIncomeTransaction = async (id: number) => {
  return customInstance<any>(`/v1/income-transactions/${id}`, { method: 'GET' });
};

const createIncomeTransaction = async (data: CreateIncomeTransactionRequest) => {
  return customInstance<any>('/v1/income-transactions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
};

const updateIncomeTransaction = async (id: number, data: CreateIncomeTransactionRequest) => {
  return customInstance<any>(`/v1/income-transactions/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
};

const deleteIncomeTransaction = async (id: number) => {
  return customInstance<any>(`/v1/income-transactions/${id}`, { method: 'DELETE' });
};

// ─── Query Keys ──────────────────────────────────────────────────────

export const incomeTransactionKeys = {
  all: ['/v1/income-transactions'] as const,
  list: (params?: ListParams) => ['/v1/income-transactions', params] as const,
  detail: (id: number) => [`/v1/income-transactions/${id}`] as const,
};

// ─── Hooks ───────────────────────────────────────────────────────────

export const useGetIncomeTransactions = (
  params?: ListParams,
  options?: { query?: Partial<UseQueryOptions> },
) => {
  return useQuery({
    queryKey: incomeTransactionKeys.list(params),
    queryFn: () => getIncomeTransactions(params),
    ...options?.query,
  } as any);
};

export const useGetIncomeTransaction = (
  id: number,
  options?: { query?: Partial<UseQueryOptions> },
) => {
  return useQuery({
    queryKey: incomeTransactionKeys.detail(id),
    queryFn: () => getIncomeTransaction(id),
    enabled: !!id,
    ...options?.query,
  } as any);
};

export const useCreateIncomeTransaction = (
  options?: {
    mutation?: UseMutationOptions<any, Error, CreateIncomeTransactionRequest>;
  },
  queryClient?: QueryClient,
) => {
  return useMutation(
    {
      mutationFn: (data: CreateIncomeTransactionRequest) => createIncomeTransaction(data),
      ...options?.mutation,
    },
    queryClient,
  );
};

export const useUpdateIncomeTransaction = (
  options?: {
    mutation?: UseMutationOptions<any, Error, { id: number; data: CreateIncomeTransactionRequest }>;
  },
  queryClient?: QueryClient,
) => {
  return useMutation(
    {
      mutationFn: ({ id, data }: { id: number; data: CreateIncomeTransactionRequest }) =>
        updateIncomeTransaction(id, data),
      ...options?.mutation,
    },
    queryClient,
  );
};

export const useDeleteIncomeTransaction = (
  options?: {
    mutation?: UseMutationOptions<any, Error, number>;
  },
  queryClient?: QueryClient,
) => {
  return useMutation(
    {
      mutationFn: (id: number) => deleteIncomeTransaction(id),
      ...options?.mutation,
    },
    queryClient,
  );
};
