/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

import type { DtoErrorResponse, PostV1Backups201 } from "../../model";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type postV1BackupsResponse201 = {
	data: PostV1Backups201;
	status: 201;
};

export type postV1BackupsResponse401 = {
	data: DtoErrorResponse;
	status: 401;
};

export type postV1BackupsResponse403 = {
	data: DtoErrorResponse;
	status: 403;
};

export type postV1BackupsResponse500 = {
	data: DtoErrorResponse;
	status: 500;
};

export type postV1BackupsResponseSuccess = postV1BackupsResponse201 & {
	headers: Headers;
};
export type postV1BackupsResponseError = (
	| postV1BackupsResponse401
	| postV1BackupsResponse403
	| postV1BackupsResponse500
) & {
	headers: Headers;
};

export type postV1BackupsResponse =
	| postV1BackupsResponseSuccess
	| postV1BackupsResponseError;

export const getPostV1BackupsUrl = () => {
	return `/v1/backups`;
};

/**
 * Trigger full database backup (pg_dump -Fc). Hanya superadmin / admin dengan modul keuangan.
 * @summary Buat backup database manual
 */
export const postV1Backups = async (
	options?: RequestInit,
): Promise<postV1BackupsResponse> => {
	return customInstance<postV1BackupsResponse>(getPostV1BackupsUrl(), {
		...options,
		method: "POST",
	});
};

export const getPostV1BackupsMutationOptions = <
	TError = DtoErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postV1Backups>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postV1Backups>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["postV1Backups"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postV1Backups>>,
		void
	> = () => {
		return postV1Backups(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostV1BackupsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postV1Backups>>
>;

export type PostV1BackupsMutationError = DtoErrorResponse;

/**
 * @summary Buat backup database manual
 */
export const usePostV1Backups = <TError = DtoErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postV1Backups>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postV1Backups>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getPostV1BackupsMutationOptions(options), queryClient);
};
