/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	DtoSuccessResponse,
	GetV1KoperasiSuppliers200,
	GetV1KoperasiSuppliersId200,
	GetV1KoperasiSuppliersParams,
	InternalModulesKoperasiPemasokCreateRequest,
	PostV1KoperasiSuppliers201,
	PutV1KoperasiSuppliersId200,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getV1KoperasiSuppliersResponse200 = {
	data: GetV1KoperasiSuppliers200;
	status: 200;
};

export type getV1KoperasiSuppliersResponseSuccess =
	getV1KoperasiSuppliersResponse200 & {
		headers: Headers;
	};

export type getV1KoperasiSuppliersResponse =
	getV1KoperasiSuppliersResponseSuccess;

export const getGetV1KoperasiSuppliersUrl = (
	params?: GetV1KoperasiSuppliersParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/koperasi/suppliers?${stringifiedParams}`
		: `/v1/koperasi/suppliers`;
};

/**
 * @summary List pemasok koperasi
 */
export const getV1KoperasiSuppliers = async (
	params?: GetV1KoperasiSuppliersParams,
	options?: RequestInit,
): Promise<getV1KoperasiSuppliersResponse> => {
	return customInstance<getV1KoperasiSuppliersResponse>(
		getGetV1KoperasiSuppliersUrl(params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetV1KoperasiSuppliersQueryKey = (
	params?: GetV1KoperasiSuppliersParams,
) => {
	return [`/v1/koperasi/suppliers`, ...(params ? [params] : [])] as const;
};

export const getGetV1KoperasiSuppliersQueryOptions = <
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
	TError = unknown,
>(
	params?: GetV1KoperasiSuppliersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetV1KoperasiSuppliersQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getV1KoperasiSuppliers>>
	> = ({ signal }) =>
		getV1KoperasiSuppliers(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1KoperasiSuppliersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getV1KoperasiSuppliers>>
>;
export type GetV1KoperasiSuppliersQueryError = unknown;

export function useGetV1KoperasiSuppliers<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
	TError = unknown,
>(
	params: undefined | GetV1KoperasiSuppliersParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
					TError,
					Awaited<ReturnType<typeof getV1KoperasiSuppliers>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1KoperasiSuppliers<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
	TError = unknown,
>(
	params?: GetV1KoperasiSuppliersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
					TError,
					Awaited<ReturnType<typeof getV1KoperasiSuppliers>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1KoperasiSuppliers<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
	TError = unknown,
>(
	params?: GetV1KoperasiSuppliersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List pemasok koperasi
 */

export function useGetV1KoperasiSuppliers<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
	TError = unknown,
>(
	params?: GetV1KoperasiSuppliersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliers>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetV1KoperasiSuppliersQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type postV1KoperasiSuppliersResponse201 = {
	data: PostV1KoperasiSuppliers201;
	status: 201;
};

export type postV1KoperasiSuppliersResponseSuccess =
	postV1KoperasiSuppliersResponse201 & {
		headers: Headers;
	};

export type postV1KoperasiSuppliersResponse =
	postV1KoperasiSuppliersResponseSuccess;

export const getPostV1KoperasiSuppliersUrl = () => {
	return `/v1/koperasi/suppliers`;
};

/**
 * @summary Tambah pemasok
 */
export const postV1KoperasiSuppliers = async (
	internalModulesKoperasiPemasokCreateRequest: InternalModulesKoperasiPemasokCreateRequest,
	options?: RequestInit,
): Promise<postV1KoperasiSuppliersResponse> => {
	return customInstance<postV1KoperasiSuppliersResponse>(
		getPostV1KoperasiSuppliersUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(internalModulesKoperasiPemasokCreateRequest),
		},
	);
};

export const getPostV1KoperasiSuppliersMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postV1KoperasiSuppliers>>,
		TError,
		{ data: InternalModulesKoperasiPemasokCreateRequest },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postV1KoperasiSuppliers>>,
	TError,
	{ data: InternalModulesKoperasiPemasokCreateRequest },
	TContext
> => {
	const mutationKey = ["postV1KoperasiSuppliers"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postV1KoperasiSuppliers>>,
		{ data: InternalModulesKoperasiPemasokCreateRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postV1KoperasiSuppliers(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostV1KoperasiSuppliersMutationResult = NonNullable<
	Awaited<ReturnType<typeof postV1KoperasiSuppliers>>
>;
export type PostV1KoperasiSuppliersMutationBody =
	InternalModulesKoperasiPemasokCreateRequest;
export type PostV1KoperasiSuppliersMutationError = unknown;

/**
 * @summary Tambah pemasok
 */
export const usePostV1KoperasiSuppliers = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postV1KoperasiSuppliers>>,
			TError,
			{ data: InternalModulesKoperasiPemasokCreateRequest },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postV1KoperasiSuppliers>>,
	TError,
	{ data: InternalModulesKoperasiPemasokCreateRequest },
	TContext
> => {
	return useMutation(
		getPostV1KoperasiSuppliersMutationOptions(options),
		queryClient,
	);
};
export type getV1KoperasiSuppliersIdResponse200 = {
	data: GetV1KoperasiSuppliersId200;
	status: 200;
};

export type getV1KoperasiSuppliersIdResponseSuccess =
	getV1KoperasiSuppliersIdResponse200 & {
		headers: Headers;
	};

export type getV1KoperasiSuppliersIdResponse =
	getV1KoperasiSuppliersIdResponseSuccess;

export const getGetV1KoperasiSuppliersIdUrl = (id: number) => {
	return `/v1/koperasi/suppliers/${id}`;
};

/**
 * @summary Detail pemasok
 */
export const getV1KoperasiSuppliersId = async (
	id: number,
	options?: RequestInit,
): Promise<getV1KoperasiSuppliersIdResponse> => {
	return customInstance<getV1KoperasiSuppliersIdResponse>(
		getGetV1KoperasiSuppliersIdUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetV1KoperasiSuppliersIdQueryKey = (id: number) => {
	return [`/v1/koperasi/suppliers/${id}`] as const;
};

export const getGetV1KoperasiSuppliersIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
	TError = unknown,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetV1KoperasiSuppliersIdQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>
	> = ({ signal }) =>
		getV1KoperasiSuppliersId(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1KoperasiSuppliersIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>
>;
export type GetV1KoperasiSuppliersIdQueryError = unknown;

export function useGetV1KoperasiSuppliersId<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
	TError = unknown,
>(
	id: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
					TError,
					Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1KoperasiSuppliersId<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
	TError = unknown,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
					TError,
					Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1KoperasiSuppliersId<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
	TError = unknown,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detail pemasok
 */

export function useGetV1KoperasiSuppliersId<
	TData = Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
	TError = unknown,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getV1KoperasiSuppliersId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetV1KoperasiSuppliersIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type putV1KoperasiSuppliersIdResponse200 = {
	data: PutV1KoperasiSuppliersId200;
	status: 200;
};

export type putV1KoperasiSuppliersIdResponseSuccess =
	putV1KoperasiSuppliersIdResponse200 & {
		headers: Headers;
	};

export type putV1KoperasiSuppliersIdResponse =
	putV1KoperasiSuppliersIdResponseSuccess;

export const getPutV1KoperasiSuppliersIdUrl = (id: number) => {
	return `/v1/koperasi/suppliers/${id}`;
};

/**
 * @summary Perbarui pemasok
 */
export const putV1KoperasiSuppliersId = async (
	id: number,
	internalModulesKoperasiPemasokCreateRequest: InternalModulesKoperasiPemasokCreateRequest,
	options?: RequestInit,
): Promise<putV1KoperasiSuppliersIdResponse> => {
	return customInstance<putV1KoperasiSuppliersIdResponse>(
		getPutV1KoperasiSuppliersIdUrl(id),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(internalModulesKoperasiPemasokCreateRequest),
		},
	);
};

export const getPutV1KoperasiSuppliersIdMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putV1KoperasiSuppliersId>>,
		TError,
		{ id: number; data: InternalModulesKoperasiPemasokCreateRequest },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putV1KoperasiSuppliersId>>,
	TError,
	{ id: number; data: InternalModulesKoperasiPemasokCreateRequest },
	TContext
> => {
	const mutationKey = ["putV1KoperasiSuppliersId"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putV1KoperasiSuppliersId>>,
		{ id: number; data: InternalModulesKoperasiPemasokCreateRequest }
	> = (props) => {
		const { id, data } = props ?? {};

		return putV1KoperasiSuppliersId(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutV1KoperasiSuppliersIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putV1KoperasiSuppliersId>>
>;
export type PutV1KoperasiSuppliersIdMutationBody =
	InternalModulesKoperasiPemasokCreateRequest;
export type PutV1KoperasiSuppliersIdMutationError = unknown;

/**
 * @summary Perbarui pemasok
 */
export const usePutV1KoperasiSuppliersId = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putV1KoperasiSuppliersId>>,
			TError,
			{ id: number; data: InternalModulesKoperasiPemasokCreateRequest },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putV1KoperasiSuppliersId>>,
	TError,
	{ id: number; data: InternalModulesKoperasiPemasokCreateRequest },
	TContext
> => {
	return useMutation(
		getPutV1KoperasiSuppliersIdMutationOptions(options),
		queryClient,
	);
};
export type deleteV1KoperasiSuppliersIdResponse200 = {
	data: DtoSuccessResponse;
	status: 200;
};

export type deleteV1KoperasiSuppliersIdResponseSuccess =
	deleteV1KoperasiSuppliersIdResponse200 & {
		headers: Headers;
	};

export type deleteV1KoperasiSuppliersIdResponse =
	deleteV1KoperasiSuppliersIdResponseSuccess;

export const getDeleteV1KoperasiSuppliersIdUrl = (id: number) => {
	return `/v1/koperasi/suppliers/${id}`;
};

/**
 * @summary Hapus pemasok
 */
export const deleteV1KoperasiSuppliersId = async (
	id: number,
	options?: RequestInit,
): Promise<deleteV1KoperasiSuppliersIdResponse> => {
	return customInstance<deleteV1KoperasiSuppliersIdResponse>(
		getDeleteV1KoperasiSuppliersIdUrl(id),
		{
			...options,
			method: "DELETE",
		},
	);
};

export const getDeleteV1KoperasiSuppliersIdMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteV1KoperasiSuppliersId>>,
		TError,
		{ id: number },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteV1KoperasiSuppliersId>>,
	TError,
	{ id: number },
	TContext
> => {
	const mutationKey = ["deleteV1KoperasiSuppliersId"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteV1KoperasiSuppliersId>>,
		{ id: number }
	> = (props) => {
		const { id } = props ?? {};

		return deleteV1KoperasiSuppliersId(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteV1KoperasiSuppliersIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteV1KoperasiSuppliersId>>
>;

export type DeleteV1KoperasiSuppliersIdMutationError = unknown;

/**
 * @summary Hapus pemasok
 */
export const useDeleteV1KoperasiSuppliersId = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteV1KoperasiSuppliersId>>,
			TError,
			{ id: number },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteV1KoperasiSuppliersId>>,
	TError,
	{ id: number },
	TContext
> => {
	return useMutation(
		getDeleteV1KoperasiSuppliersIdMutationOptions(options),
		queryClient,
	);
};
