/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoClassGroupReportSummary {
	payment_rate?: string;
	total_billed?: number;
	total_paid?: number;
	total_students?: number;
	total_unpaid?: number;
}
