/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export type DtoUpdateUserRequestRole =
	(typeof DtoUpdateUserRequestRole)[keyof typeof DtoUpdateUserRequestRole];

export const DtoUpdateUserRequestRole = {
	superadmin: "superadmin",
	admin_administrasi: "admin_administrasi",
	admin_keuangan: "admin_keuangan",
	kepala_sekolah: "kepala_sekolah",
	yayasan: "yayasan",
} as const;
