/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */

export interface DtoWithdrawalResponse {
	admin_fee?: number;
	amount?: number;
	net_amount?: number;
	remaining_balance?: number;
}
