/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import type { DtoSuccessResponse } from "./dtoSuccessResponse";
import type { DtoUserResponse } from "./dtoUserResponse";

export type GetV1UsersId200 = DtoSuccessResponse & {
	data?: DtoUserResponse;
};
