/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Alizzah Manajemen API
 * API for Alizzah School Management System
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1KoperasiMiscTransactions200,
  GetV1KoperasiMiscTransactionsId200,
  GetV1KoperasiMiscTransactionsParams,
  LainlainCreateRequest,
  PostV1KoperasiMiscTransactions201
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1KoperasiMiscTransactionsResponse200 = {
  data: GetV1KoperasiMiscTransactions200
  status: 200
}

export type getV1KoperasiMiscTransactionsResponseSuccess = (getV1KoperasiMiscTransactionsResponse200) & {
  headers: Headers;
};
;

export type getV1KoperasiMiscTransactionsResponse = (getV1KoperasiMiscTransactionsResponseSuccess)

export const getGetV1KoperasiMiscTransactionsUrl = (params?: GetV1KoperasiMiscTransactionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/koperasi/misc-transactions?${stringifiedParams}` : `/v1/koperasi/misc-transactions`
}

/**
 * @summary List transaksi lain-lain
 */
export const getV1KoperasiMiscTransactions = async (params?: GetV1KoperasiMiscTransactionsParams, options?: RequestInit): Promise<getV1KoperasiMiscTransactionsResponse> => {

  return customInstance<getV1KoperasiMiscTransactionsResponse>(getGetV1KoperasiMiscTransactionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1KoperasiMiscTransactionsQueryKey = (params?: GetV1KoperasiMiscTransactionsParams,) => {
    return [
    `/v1/koperasi/misc-transactions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1KoperasiMiscTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError = unknown>(params?: GetV1KoperasiMiscTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1KoperasiMiscTransactionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>> = ({ signal }) => getV1KoperasiMiscTransactions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1KoperasiMiscTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>>
export type GetV1KoperasiMiscTransactionsQueryError = unknown


export function useGetV1KoperasiMiscTransactions<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError = unknown>(
 params: undefined |  GetV1KoperasiMiscTransactionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>,
          TError,
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1KoperasiMiscTransactions<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError = unknown>(
 params?: GetV1KoperasiMiscTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>,
          TError,
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1KoperasiMiscTransactions<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError = unknown>(
 params?: GetV1KoperasiMiscTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List transaksi lain-lain
 */

export function useGetV1KoperasiMiscTransactions<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError = unknown>(
 params?: GetV1KoperasiMiscTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1KoperasiMiscTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1KoperasiMiscTransactionsResponse201 = {
  data: PostV1KoperasiMiscTransactions201
  status: 201
}

export type postV1KoperasiMiscTransactionsResponseSuccess = (postV1KoperasiMiscTransactionsResponse201) & {
  headers: Headers;
};
;

export type postV1KoperasiMiscTransactionsResponse = (postV1KoperasiMiscTransactionsResponseSuccess)

export const getPostV1KoperasiMiscTransactionsUrl = () => {




  return `/v1/koperasi/misc-transactions`
}

/**
 * @summary Catat transaksi lain-lain (pemasukan/pengeluaran)
 */
export const postV1KoperasiMiscTransactions = async (lainlainCreateRequest: LainlainCreateRequest, options?: RequestInit): Promise<postV1KoperasiMiscTransactionsResponse> => {

  return customInstance<postV1KoperasiMiscTransactionsResponse>(getPostV1KoperasiMiscTransactionsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lainlainCreateRequest,)
  }
);}




export const getPostV1KoperasiMiscTransactionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1KoperasiMiscTransactions>>, TError,{data: LainlainCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1KoperasiMiscTransactions>>, TError,{data: LainlainCreateRequest}, TContext> => {

const mutationKey = ['postV1KoperasiMiscTransactions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1KoperasiMiscTransactions>>, {data: LainlainCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1KoperasiMiscTransactions(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1KoperasiMiscTransactionsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1KoperasiMiscTransactions>>>
    export type PostV1KoperasiMiscTransactionsMutationBody = LainlainCreateRequest
    export type PostV1KoperasiMiscTransactionsMutationError = unknown

    /**
 * @summary Catat transaksi lain-lain (pemasukan/pengeluaran)
 */
export const usePostV1KoperasiMiscTransactions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1KoperasiMiscTransactions>>, TError,{data: LainlainCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1KoperasiMiscTransactions>>,
        TError,
        {data: LainlainCreateRequest},
        TContext
      > => {
      return useMutation(getPostV1KoperasiMiscTransactionsMutationOptions(options), queryClient);
    }
    export type getV1KoperasiMiscTransactionsIdResponse200 = {
  data: GetV1KoperasiMiscTransactionsId200
  status: 200
}

export type getV1KoperasiMiscTransactionsIdResponseSuccess = (getV1KoperasiMiscTransactionsIdResponse200) & {
  headers: Headers;
};
;

export type getV1KoperasiMiscTransactionsIdResponse = (getV1KoperasiMiscTransactionsIdResponseSuccess)

export const getGetV1KoperasiMiscTransactionsIdUrl = (id: number,) => {




  return `/v1/koperasi/misc-transactions/${id}`
}

/**
 * @summary Detail transaksi lain-lain
 */
export const getV1KoperasiMiscTransactionsId = async (id: number, options?: RequestInit): Promise<getV1KoperasiMiscTransactionsIdResponse> => {

  return customInstance<getV1KoperasiMiscTransactionsIdResponse>(getGetV1KoperasiMiscTransactionsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1KoperasiMiscTransactionsIdQueryKey = (id: number,) => {
    return [
    `/v1/koperasi/misc-transactions/${id}`
    ] as const;
    }


export const getGetV1KoperasiMiscTransactionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1KoperasiMiscTransactionsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>> = ({ signal }) => getV1KoperasiMiscTransactionsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1KoperasiMiscTransactionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>>
export type GetV1KoperasiMiscTransactionsIdQueryError = unknown


export function useGetV1KoperasiMiscTransactionsId<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1KoperasiMiscTransactionsId<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1KoperasiMiscTransactionsId<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Detail transaksi lain-lain
 */

export function useGetV1KoperasiMiscTransactionsId<TData = Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1KoperasiMiscTransactionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1KoperasiMiscTransactionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






